// page頁面 上方
function PageHeader() {
    document.writeln("<!-- 電腦板 header ------------------------------------------------------------------------>");
    document.writeln("  <!-- login ------------------------------------>");
    document.writeln("  <div class=\'container-fluid d-none d-md-block p-0 bgc-loginbar-color\'>");
    document.writeln("    <div class=\'container\'>");
    document.writeln("      <div class=\'row py-1\'>");
    document.writeln("        <div class=\'col-12 text-right\'>");
    document.writeln("          <!-- 註冊 -->");
    document.writeln("          <a href=\'#modal-example1\' class=\'input-size ml-2 text-center mr-1\' uk-toggle>");
    document.writeln("            <img class=\'img-fluid\' src=\'../卡-img/登入條/註冊.png\' alt=\'\'>");
    document.writeln("          </a>");
    document.writeln("");
    document.writeln("          <div id=\'modal-example1\' uk-modal>");
    document.writeln("            <div class=\'uk-modal-dialog w3-round-large\'>");
    document.writeln("              <div class=\'px-3 py-1 bgc-loginbar-color  row\' style=\' border-radius: 8px 8px 0 0;\'>");
    document.writeln("                <span class=\'pl-2 centerCenter font-weight-bold fsz-13\'>加入會員</span>");
    document.writeln("                <button class=\'uk-modal-close-default text-dark\' type=\'button\' uk-close></button>");
    document.writeln("              </div>");
    document.writeln("              <div class=\'text-secondary bg-theme px-2 pt-3 pb-2\'>");
    document.writeln("                <!--  -->");
    document.writeln("                <div class=\'row centerCenter px-4 py-2\'>");
    document.writeln("                  <!-- 帳號 -->");
    document.writeln("                  <div class=\'col-3 py-2 text-light\'>帳號 *</div>");
    document.writeln("                  <div class=\'col-9 py-2\'>");
    document.writeln("                    <input type=\'text\'");
    document.writeln("                      class=\'w-100 px-3 py-1 text-secondary fsz-08 bg-theme border border-secondary w3-round-medium\'");
    document.writeln("                      placeholder=\'4~10碼英文或數字組合\' onfocus=\'this.placeholder = \'\'\'");
    document.writeln("                      onblur=\'this.placeholder = \'4~10碼英文或數字組合\'\' />");
    document.writeln("                  </div>");
    document.writeln("                  <!-- 密碼 -->");
    document.writeln("                  <div class=\'col-3 py-2 text-light\'>密碼 *</div>");
    document.writeln("                  <div class=\'col-9 py-2\'>");
    document.writeln("                    <input type=\'text\'");
    document.writeln("                      class=\'w-100 px-3 py-1 text-secondary fsz-08 bg-theme border border-secondary w3-round-medium\'");
    document.writeln("                      placeholder=\'6~13碼英文或數字組合\' onfocus=\'this.placeholder = \'\'\'");
    document.writeln("                      onblur=\'this.placeholder = \'6~13碼英文或數字組合\'\' />");
    document.writeln("                  </div>");
    document.writeln("                  <!-- 確認密碼 -->");
    document.writeln("                  <div class=\'col-3 py-2 text-light\'>確認密碼 *</div>");
    document.writeln("                  <div class=\'col-9 py-2\'>");
    document.writeln("                    <input type=\'text\'");
    document.writeln("                      class=\'w-100 px-3 py-1 text-secondary fsz-08 bg-theme border border-secondary w3-round-medium\'");
    document.writeln("                      placeholder=\'請再次輸入密碼\' onfocus=\'this.placeholder = \'\'\' onblur=\'this.placeholder = \'請再次輸入密碼\'\' />");
    document.writeln("                  </div>");
    document.writeln("                  <!-- 姓名 -->");
    document.writeln("                  <div class=\'col-3 py-2 text-light\'>姓名 *</div>");
    document.writeln("                  <div class=\'col-9 py-2\'>");
    document.writeln("                    <input type=\'text\'");
    document.writeln("                      class=\'w-100 px-3 py-1 text-secondary fsz-08 bg-theme border border-secondary w3-round-medium\'");
    document.writeln("                      placeholder=\'請輸入正確性名\' onfocus=\'this.placeholder = \'\'\' onblur=\'this.placeholder = \'請輸入正確性名\'\' />");
    document.writeln("                  </div>");
    document.writeln("                  <!-- LINE ID -->");
    document.writeln("                  <div class=\'col-3 py-2 text-light\'>LINE ID *</div>");
    document.writeln("                  <div class=\'col-9 py-2\'>");
    document.writeln("                    <input type=\'text\'");
    document.writeln("                      class=\'w-100 px-3 py-1 text-secondary fsz-08 bg-theme border border-secondary w3-round-medium\'");
    document.writeln("                      placeholder=\'請留下正確ID\' onfocus=\'this.placeholder = \'\'\' onblur=\'this.placeholder = \'請留下正確ID\'\' />");
    document.writeln("                  </div>");
    document.writeln("                  <!-- 推薦碼 -->");
    document.writeln("                  <div class=\'col-3 py-2 text-light\'>推薦碼</div>");
    document.writeln("                  <div class=\'col-9 py-2\'>");
    document.writeln("                    <input type=\'text\'");
    document.writeln("                      class=\'w-100 px-3 py-1 text-secondary fsz-08 bg-theme border border-secondary w3-round-medium\'");
    document.writeln("                      placeholder=\'非必填\' onfocus=\'this.placeholder = \'\'\' onblur=\'this.placeholder = \'非必填\'\' />");
    document.writeln("                  </div>");
    document.writeln("                  <!-- 手機號碼 -->");
    document.writeln("                  <div class=\'col-3 py-2 text-light\'>手機號碼</div>");
    document.writeln("                  <div class=\'col-9 py-2\'>");
    document.writeln("                    <input type=\'text\' style=\'width: 66%;\'");
    document.writeln("                      class=\'px-3 py-1 text-secondary fsz-08 bg-theme border border-secondary w3-round-medium\'");
    document.writeln("                      placeholder=\'請輸入有效手機號碼\' onfocus=\'this.placeholder = \'\'\' onblur=\'this.placeholder = \'請輸入有效手機號碼\'\' />");
    document.writeln("                    <input type=\'submit\' value=\'發送驗證碼\'");
    document.writeln("                      class=\'px-2 py-1 text-light fsz-08 text-center bg-theme border border-danger w3-round-medium\'");
    document.writeln("                      style=\'width: 32%;\' />");
    document.writeln("                  </div>");
    document.writeln("                  <!-- 驗證碼 -->");
    document.writeln("                  <div class=\'col-3 py-2 text-light\'>驗證碼</div>");
    document.writeln("                  <div class=\'col-9 py-2\'>");
    document.writeln("                    <input type=\'text\'");
    document.writeln("                      class=\'w-100 px-3 py-1 text-secondary fsz-08 bg-theme border border-secondary w3-round-medium\'");
    document.writeln("                      placeholder=\'虛擬帳號(儲值管道)\' onfocus=\'this.placeholder = \'\'\'");
    document.writeln("                      onblur=\'this.placeholder = \'虛擬帳號(儲值管道)\'\' />");
    document.writeln("                  </div>");
    document.writeln("                  <!-- 註冊 -->");
    document.writeln("                  <div class=\'col-12 py-2 pb-2\'>");
    document.writeln("                    <button");
    document.writeln("                      class=\'btn w3-round-medium w3-medium font-weight-bold bgc-loginbar-color px-5 border-0 lp1 w-100\'>註冊</button>");
    document.writeln("                  </div>");
    document.writeln("                  <div class=\'col-12 pt-2\'>");
    document.writeln("                    <img src=\'../卡-img/登入條/優惠1.jpg\' alt=\'\'>");
    document.writeln("                  </div>");
    document.writeln("                </div>");
    document.writeln("              </div>");
    document.writeln("            </div>");
    document.writeln("          </div>");
    document.writeln("          <!-- 帳號 -->");
    document.writeln("          <input type=\'text\' class=\'px-2\' placeholder=\'用戶名(ID)\' onfocus=\'this.placeholder = \'\'\'");
    document.writeln("            onblur=\'this.placeholder = \'用戶名(ID)\'\' />");
    document.writeln("          <!-- 密碼 -->");
    document.writeln("          <input type=\'password\' class=\'px-2\' placeholder=\'密碼\' onfocus=\'this.placeholder = \'\'\'");
    document.writeln("            onblur=\'this.placeholder = \'密碼\'\' />");
    document.writeln("          <!-- 登入 -->");
    document.writeln("          <a href=\'../page/indexLogin.html\' class=\'input-size ml-2 text-center mr-1\' uk-toggle>");
    document.writeln("            <img class=\'img-fluid\' src=\'../卡-img/登入條/登入.png\' alt=\'\'>");
    document.writeln("          </a>");
    document.writeln("        </div>");
    document.writeln("      </div>");
    document.writeln("    </div>");
    document.writeln("  </div>");
    document.writeln(" <!-- LG Navigation Bars ------------------------------------>");
    document.writeln("<div class=\'container-fluid d-none d-lg-block p-0 bgc-header-color NavigationBorder\'>");
    document.writeln("    <div class=\'container\'>");
    document.writeln("        <div class=\'row\' style=\'align-items:center;\'>");
    document.writeln("            <div class=\'col-3 centerCenter\'>");
    document.writeln("                <a class=\'\' href=\'../index.html\'><img class=\'\' src=\'../卡-img/桌機index_img/logo.png\'></a>");
    document.writeln("            </div>");
    document.writeln("            <div class=\'col-9\'>");
    document.writeln("                <div class=\'row mx-auto\'>");
    document.writeln("                    <a class=\'col py-2 centerCenter\' href=\'../page/LiveCasino.html\'>");
    document.writeln("                        <img class=\'img-fluid AnimaTion1\' src=\'../卡-img/桌機index_img/icon1.png\' alt=\'\'>");
    document.writeln("                    </a>");
    document.writeln("                    <a class=\'col py-2 centerCenter\' href=\'../page/Sport.html\'>");
    document.writeln("                        <img class=\'img-fluid AnimaTion2\' src=\'../卡-img/桌機index_img/icon2.png\' alt=\'\'>");
    document.writeln("                    </a>");
    document.writeln("                    <a class=\'col py-2 centerCenter\' href=\'../page/Chess.html\'>");
    document.writeln("                        <img class=\'img-fluid AnimaTion3\' src=\'../卡-img/桌機index_img/icon3.png\' alt=\'\'>");
    document.writeln("                    </a>");
    document.writeln("                    <a class=\'col py-2 centerCenter\' href=\'../page/Slot.html\'>");
    document.writeln("                        <img class=\'img-fluid AnimaTion4\' src=\'../卡-img/桌機index_img/icon4.png\' alt=\'\'></a>");
    document.writeln("                    <a class=\'col py-2 centerCenter\' href=\'../page/Bingo.html\'>");
    document.writeln("                        <img class=\'img-fluid AnimaTion5\' src=\'../卡-img/桌機index_img/icon5.png\' alt=\'\'>");
    document.writeln("                    </a>");
    document.writeln("                    <a class=\'col py-2 centerCenter\' href=\'../page/Fish.html\'>");
    document.writeln("                        <img class=\'img-fluid AnimaTion6\' src=\'../卡-img/桌機index_img/icon6.png\' alt=\'\'>");
    document.writeln("                    </a>");
    document.writeln("                    <a class=\'col py-2 centerCenter\' href=\'../page/Promotion.html\'>");
    document.writeln("                        <img class=\'img-fluid AnimaTion7\' src=\'../卡-img/桌機index_img/icon7.png\' alt=\'\'>");
    document.writeln("                    </a>");
    document.writeln("                    <a class=\'col py-2 centerCenter\' href=\'../page/Movie.html\'>");
    document.writeln("                        <img class=\'img-fluid AnimaTion8\' src=\'../卡-img/桌機index_img/icon8.png\' alt=\'\'>");
    document.writeln("                    </a>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("        </div>");
    document.writeln("    </div>");
    document.writeln("</div>");
    document.writeln("<!-- 維護時間 -->");
    document.writeln("<div class=\'dropleft d-none d-md-block position-absolute\'>");
    document.writeln("    <!-- BMaintenanceTime 控制項 -->");
    document.writeln("    <a class=\'btn BMaintenanceTime p-0\' data-toggle=\'dropdown\' aria-haspopup=\'true\' aria-expanded=\'false\'");
    document.writeln("        id=\'dropdownMenuReference\'><img src=\'../卡-img/桌機index_img/維修.png\' class=\'img-fluid p-0 m-0\' alt=\'\'></a>");
    document.writeln("    <div class=\'dropdown-menu px-3 bgc-header-color\' aria-labelledby=\'dropdownMenuReference\'");
    document.writeln("        style=\'height: 300px; overflow: scroll;overflow-x: hidden;\'>");
    document.writeln("        <div class=\'pt-3\'>");
    document.writeln("            <p class=\'text-center text-light\'>緊急維修</p>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>幸運棋牌</p>");
    document.writeln("            <p class=\'text-center text-light\'>01/12/2020 02:00:00</p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3\'>");
    document.writeln("            <p class=\'text-center\' style=\'height: 1px;width: 100%;background: #555;\'></p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-center\'>星期一</p>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>9K彩票</p>");
    document.writeln("            <p class=\'text-center\'>00:00 至 00:00</p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>Super體育</p>");
    document.writeln("            <p class=\'text-center\'>12:30 至 16:00</p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>WM百家樂</p>");
    document.writeln("            <p class=\'text-center\'>12:00 至 14:30</p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>任你博體育</p>");
    document.writeln("            <p class=\'text-center\'>16:00 至 18:00</p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>六合彩539</p>");
    document.writeln("            <p class=\'text-center\'>12:30 至 16:30</p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>幸運棋牌</p>");
    document.writeln("            <p class=\'text-center\'>23:00 至 00:00</p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>歐博百家樂</p>");
    document.writeln("            <p class=\'text-center\'>08:00 至 12:00</p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>沙龍百家樂</p>");
    document.writeln("            <p class=\'text-center\'>10:00 至 12:30</p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-center\' style=\'height: 1px;width: 100%;background: #555;\'></p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-center\'>星期二</p>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>RTG電子</p>");
    document.writeln("            <p class=\'text-center\'>07:00 至 09:00</p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-center\' style=\'height: 1px;width: 100%;background: #555;\'></p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-center\'>星期三</p>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>DG電子</p>");
    document.writeln("            <p class=\'text-center\'>07:00 至 10:00</p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>MG棋牌</p>");
    document.writeln("            <p class=\'text-center\'>11:00 至 13:00</p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-center\' style=\'height: 1px;width: 100%;background: #555;\'></p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-center\'>星期四</p>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>SimplePlay電子</p>");
    document.writeln("            <p class=\'text-center\'>11:00 至 13:30</p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-center\' style=\'height: 1px;width: 100%;background: #555;\'></p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-center\'>星期五</p>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>SimplePlay電子</p>");
    document.writeln("            <p class=\'text-center\'>15:00 至 19:00</p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-center\' style=\'height: 1px;width: 100%;background: #555;\'></p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'py-3 text-light\'>");
    document.writeln("            <p class=\'text-center\'>星期日</p>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>BNG電子</p>");
    document.writeln("            <p class=\'text-center\'>14:30 至 02:30</p>");
    document.writeln("        </div>");
    document.writeln("    </div>");
    document.writeln("</div>");
    document.writeln("<!-- 聯繫我們 -->");
    document.writeln("<div class=\'d-none d-md-block\'>");
    document.writeln("    <div class=\'contactUs p-1 rounded-right w3-round-large\'>");
    document.writeln("        <!-- 24Hr -->");
    document.writeln("        <a href=\'https://line.me/R/ti/p/%40322gtrqp\' class=\'btn px-0 pt-1 pb-3 m-0 bg-cover\'");
    document.writeln("            style=\'border-bottom: 1px solid #000;\' target=\'_blank\'>");
    document.writeln("            <img src=\'../卡-img/桌機index_img/維修1.png\' class=\'img-fluid\' alt=\'\'>");
    document.writeln("        </a>");
    document.writeln("        <!-- mail -->");
    document.writeln("        <a href=\'#modal-example\' class=\'btn px-1 pt-1 pb-1 pr-2 m-0 bg-cover centerCenter\' uk-toggle>");
    document.writeln("            <img class=\'img-fluid px-1 centerCenter\' src=\'../卡-img/桌機index_img/email.png\' alt=\'\'>");
    document.writeln("        </a>");
    document.writeln("        <!-- 2 modal -->");
    document.writeln("        <div id=\'modal-example\' uk-modal>");
    document.writeln("            <div class=\'uk-modal-dialog uk-modal-body bgc-header-color\'>");
    document.writeln("                <h2 class=\'uk-modal-title text-light\'>意見反饋</h2>");
    document.writeln("                <button class=\'uk-modal-close-default text-light uk-close-large\' style=\'right: 15px; top: 15px;\'");
    document.writeln("                    type=\'button\' uk-close></button>");
    document.writeln("                <!-- table -->");
    document.writeln("                <table class=\'uk-table text-light\'>");
    document.writeln("                    <thead>");
    document.writeln("                        <tr>");
    document.writeln("                            <th class=\'text-light\'></th>");
    document.writeln("                            <th class=\'text-light\'>極差</th>");
    document.writeln("                            <th class=\'text-light\'>很差</th>");
    document.writeln("                            <th class=\'text-light\'>普通</th>");
    document.writeln("                            <th class=\'text-light\'>很好</th>");
    document.writeln("                            <th class=\'text-light\'>極好</th>");
    document.writeln("                        </tr>");
    document.writeln("                    </thead>");
    document.writeln("                    <tbody>");
    document.writeln("                        <tr>");
    document.writeln("                            <td>客服服務</td>");
    document.writeln("                            <td><input type=\'radio\' name=\'1\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'1\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'1\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'1\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'1\' id=\'\'></td>");
    document.writeln("                        </tr>");
    document.writeln("                        <tr>");
    document.writeln("                            <td>提款速度</td>");
    document.writeln("                            <td><input type=\'radio\' name=\'2\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'2\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'2\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'2\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'2\' id=\'\'></td>");
    document.writeln("                        </tr>");
    document.writeln("                        <tr>");
    document.writeln("                            <td>操作界面</td>");
    document.writeln("                            <td><input type=\'radio\' name=\'3\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'3\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'3\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'3\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'3\' id=\'\'></td>");
    document.writeln("                        </tr>");
    document.writeln("                        <tr>");
    document.writeln("                            <td>網路連結速度</td>");
    document.writeln("                            <td><input type=\'radio\' name=\'4\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'4\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'4\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'4\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'4\' id=\'\'></td>");
    document.writeln("                        </tr>");
    document.writeln("                    </tbody>");
    document.writeln("                </table>");
    document.writeln("                <div class=\'row pb-3\'>");
    document.writeln("                    <div class=\'col-3 text-light ml-3\'>意見</div>");
    document.writeln("                    <div class=\'flex-grow-1\'>");
    document.writeln("                        <textarea name=\'\' id=\'\' cols=\'39\' rows=\'5\'></textarea>");
    document.writeln("                    </div>");
    document.writeln("                </div>");
    document.writeln("                <p class=\'uk-text-right\'>");
    document.writeln("                    <button class=\'uk-button bg-i-gold text-black\' type=\'button\'>提交</button>");
    document.writeln("                </p>");
    document.writeln("            </div>");
    document.writeln("        </div>");
    document.writeln("    </div>");
    document.writeln("</div>");
    document.writeln("<!-- 手機板 header ------------------------------------------------------------------------>");
    document.writeln("<!-- MD Navigation Bars ------------------------------------>");
    document.writeln("<div class=\'container-fluid p-0 d-lg-none bgc-header-color MdNavigationBorder\'>");
    document.writeln("    <div class=\'container\'>");
    document.writeln("        <div class=\'row py-2\' style=\'align-items: center;\'>");
    document.writeln("            <!-- 漢堡圖 -->");
    document.writeln("            <div class=\'col-3 text-left\'>");
    document.writeln("                <!-- HamburgBtn -->");
    document.writeln("                <i class=\'fas fa-bars fa-2x\' style=\'color:#f1cd6d\' id=\'HamburgBtn\' data-toggle=\'modal\'");
    document.writeln("                    data-target=\'#exampleModal0\'></i>");
    document.writeln("<!-- HamburgBtn modal -->");
    document.writeln("                    <div class=\'modal\' id=\'exampleModal0\'>");
    document.writeln("                        <div id=\'showMenu p-0\' class=\'modal-dialog\'>");
    document.writeln("                            <div class=\'showMenuList modal-content\'>");
    document.writeln("                                <div class=\'modal-body p-0 m-0 slotBg-v text-light\'>");
    document.writeln("                                    <!-- user -->");
    document.writeln("                                    <div class=\'row m-0 px-5 py-3 bg-theme w3-border-yellow\'>");
    document.writeln("                                        <div class=\'col-12 centerCenter\'>");
    document.writeln("                                            <img class=\'centerCenter img-fluid\' src=\'../卡-img/桌機index_img/h漢堡/0user.png\'");
    document.writeln("                                                alt=\'\'>");
    document.writeln("                                            <p class=\'text-center pt-1\'>user</p>");
    document.writeln("                                        </div>");
    document.writeln("                                    </div>");
    document.writeln("                                    <!-- 0.首頁 -->");
    document.writeln("                                    <div class=\'row px-5 py-3\'>");
    document.writeln("                                        <a href=\'../index.html\' class=\'col-12 text-decoration-none\'>");
    document.writeln("                                            <img class=\'img-fluid\' src=\'../卡-img/桌機index_img/h漢堡/0首頁.png\' alt=\'\'>");
    document.writeln("                                            <span class=\'text-light pl-3\'>首頁</span>");
    document.writeln("                                        </a>");
    document.writeln("                                    </div>");
    document.writeln("                                    <!-- 1.優惠活動 -->");
    document.writeln("                                    <div class=\'row px-5 py-3\'>");
    document.writeln("                                        <a href=\'./page/Promotion.html\' class=\'col-12 text-decoration-none\'>");
    document.writeln("                                            <img class=\'img-fluid\' src=\'../卡-img/桌機index_img/h漢堡/1優惠.png\' alt=\'\'>");
    document.writeln("                                            <span class=\'text-light pl-3\'>優惠活動</span>");
    document.writeln("                                        </a>");
    document.writeln("                                    </div>");
    document.writeln("                                    <!-- 2遊戲介紹 -->");
    document.writeln("                                    <div class=\'row px-5 py-3\'>");
    document.writeln("                                        <a href=\'../Features page/GameIntro.html\' class=\'col-12 text-decoration-none\'>");
    document.writeln("                                            <img class=\'img-fluid\' src=\'../卡-img/桌機index_img/h漢堡/2遊戲介紹.png\' alt=\'\'>");
    document.writeln("                                            <span class=\'text-light pl-3\'>遊戲介紹</span>");
    document.writeln("                                        </a>");
    document.writeln("                                    </div>");
    document.writeln("                                    <!-- 3.部落格 -->");
    document.writeln("                                    <div class=\'row px-5 py-3\'>");
    document.writeln("                                        <a href=\'../blog/AllBlog.html\' class=\'col-12 text-decoration-none\'>");
    document.writeln("                                            <img class=\'img-fluid\' src=\'../卡-img/桌機index_img/h漢堡/3部落格.png\' alt=\'\'>");
    document.writeln("                                            <span class=\'text-light pl-3\'>部落格</span>");
    document.writeln("                                        </a>");
    document.writeln("                                    </div>");
    document.writeln("                                    <!-- 4公告 -->");
    document.writeln("                                    <div class=\'row px-5 py-3\'>");
    document.writeln("                                        <a href=\'../header page/3FAQ.html\' class=\'col-12 text-decoration-none\'>");
    document.writeln("                                            <img class=\'img-fluid\' src=\'../卡-img/桌機index_img/h漢堡/4公告.png\' alt=\'\'>");
    document.writeln("                                            <span class=\'text-light pl-3\'>公告</span>");
    document.writeln("                                        </a>");
    document.writeln("                                    </div>");
    document.writeln("                                    <!-- 5.維護時間 -->");
    document.writeln("                                    <div class=\'row px-5 py-3\'>");
    document.writeln("                                        <a href=\'../header page/4RepairTime.html\' class=\'col-12 text-decoration-none\'>");
    document.writeln("                                            <img class=\'img-fluid\' src=\'../卡-img/桌機index_img/h漢堡/5維護.png\' alt=\'\'>");
    document.writeln("                                            <span class=\'text-light pl-3\'>維護時間</span>");
    document.writeln("                                        </a>");
    document.writeln("                                    </div>");
    document.writeln("                                    <!-- 6.APP下載 -->");
    document.writeln("                                    <div class=\'row px-5 py-3\'>");
    document.writeln("                                        <a href=\'../header page/2AppDownload.html\' class=\'col-12 text-decoration-none\'>");
    document.writeln("                                            <img class=\'img-fluid\' src=\'../卡-img/桌機index_img/h漢堡/6app下載.png\' alt=\'\'>");
    document.writeln("                                            <span class=\'text-light pl-3\'>APP下載</span>");
    document.writeln("                                        </a>");
    document.writeln("                                    </div>");
    document.writeln("                                    <!-- 7.合營代理 -->");
    document.writeln("                                    <div class=\'row px-5 py-3\'>");
    document.writeln("                                        <a href=\'../header page/0Agent.html\' class=\'col-12 text-decoration-none\'>");
    document.writeln("                                            <img class=\'img-fluid\' src=\'../卡-img/桌機index_img/h漢堡/7代理加盟.png\' alt=\'\'>");
    document.writeln("                                            <span class=\'text-light pl-3\'>合營代理</span>");
    document.writeln("                                        </a>");
    document.writeln("                                    </div>");
    document.writeln("                                    <!-- 8.關於卡利 -->");
    document.writeln("                                    <div class=\'row px-5 py-3\'>");
    document.writeln("                                        <a href=\'../header page/1AboutUs.html\' class=\'col-12 text-decoration-none\'>");
    document.writeln("                                            <img class=\'img-fluid\' src=\'../卡-img/桌機index_img/h漢堡/8關於.png\' alt=\'\'>");
    document.writeln("                                            <span class=\'text-light pl-3\'>關於卡利</span>");
    document.writeln("                                        </a>");
    document.writeln("                                    </div>");
    document.writeln("                                    <!-- 登出 -->");
    document.writeln("                                        <div class=\'row p-5\'>");
    document.writeln("                                            <a class=\'col-12 text-decoration-none\' href=\'./index.html\'>");
    document.writeln("                                                <span class=\'text-light\'>登出</span>");
    document.writeln("                                            </a>");
    document.writeln("                                        </div>");
    document.writeln("                                </div>");
    document.writeln("                            </div>");
    document.writeln("                        </div>");
    document.writeln("                    </div>");
    document.writeln("            </div>");
    document.writeln("            <!-- LOGO -->");
    document.writeln("            <div class=\'col-6 text-center\'>");
    document.writeln("                <div class=\'text-center\' style=\'margin-left: -5%;\'><a href=\'../index.html\'><img");
    document.writeln("                            src=\'../卡-img/手機index_img/logo.png\' alt=\'\' class=\'img-fluid\'></a></div>");
    document.writeln("            </div>");
    document.writeln("        <!-- 24HR客服 -->");
    document.writeln("        <div class=\'col-3 p-1 pl-3\'>");
    document.writeln("          <div class=\'text-right\'><img id=\'hrServiceBtn\' src=\'../卡-img/手機index_img/24h.png\' alt=\'\' class=\'img-fluid\'");
    document.writeln("              data-toggle=\'modal\' data-target=\'#exampleModal\'></div>");
    document.writeln("        </div>");
    document.writeln("            <!-- 24HR客服 Modal -->");
    document.writeln("                <!-- HamburgBtn modal -->");
    document.writeln("            <div class=\'modal fade\' id=\'exampleModal\' tabindex=\'-1\' role=\'dialog\'");
    document.writeln("                aria-labelledby=\'exampleModalLabel\' aria-hidden=\'true\'>");
    document.writeln("                <div class=\'modal-dialog\' role=\'document\'>");
    document.writeln("                    <div class=\'modal-content mx-auto w-75\'");
    document.writeln("                        style=\'position: fixed !important;top: 6% !important; left: 10% !important;right: 10% !important;\'>");
    document.writeln("                        <!-- 聯繫我們 -->");
    document.writeln("                        <div class=\'modal-header bgc-header-color\'>");
    document.writeln("                            <p class=\'modal-title m-auto w3-text-white\' id=\'exampleModalLabel\'");
    document.writeln("                                style=\'font-size: 1.2rem !important;\'>聯繫我們");
    document.writeln("                            </p>");
    document.writeln("                        </div>");
    document.writeln("                        <!-- img -->");
    document.writeln("                        <div class=\'modal-body p-0\'>");
    document.writeln("                            <img src=\'../卡-img/手機index_img/24x7.png\' alt=\'\' class=\'w-100\'>");
    document.writeln("                        </div>");
    document.writeln("                        <!-- Close -->");
    document.writeln("                        <div class=\'w-100 bgc-header-color\'>");
    document.writeln("                            <div class=\'py-2 text-center w3-text-white\' style=\'cursor: pointer;\'");
    document.writeln("                                data-dismiss=\'modal\'>Close</div>");
    document.writeln("                        </div>");
    document.writeln("                    </div>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("        </div>");
    document.writeln("    </div>");
    document.writeln("</div>");
    document.writeln("<!-- 相通 ------------------------------------------------------------------------>");
    document.writeln("<!-- marquee -->");
    document.writeln("<div class=\'container-fluid p-0 m-0\'>");
    document.writeln("    <div class=\'bgc-flex\' style=\'background-color: black; height: 28px;\'>");
    document.writeln("        <div class=\'row p-0 m-0\'>");
    document.writeln("            <div class=\'text-center\' style=\'width: 10%;\'>");
    document.writeln("                <img src=\'../img/手機index_img/marqueeA.png\' class=\'img-fluid\' alt=\'\'>");
    document.writeln("            </div>");
    document.writeln("            <div class=\'\' style=\'width: 88%;\'>");
    document.writeln("                <marquee direction=\'left\' height=\'10\' scrollamount=\'5\' behavior=\'left\' class=\'text-light h-100\'");
    document.writeln("                    onmouseover=\'this.stop()\' onmouseout=\'this.start()\'>");
    document.writeln("                    【維護公告】 親愛的娛樂城會員您好，【幸運棋牌-維護通知】即刻起進行線路調整緊急維護，維護完成時間待定，造成不便敬請見諒    【存款公告】");
    document.writeln("                    開通超商存款後以第一次繳費地點為綁定超商，若後續要更換繳費超商，請先提前告知與客服申請，否則導致造成資金損失風險需自行承擔，若為附近的超商地點繳費提前告知即可    【存款公告】");
    document.writeln("                    敬愛的卡利會員您好，卡利娛樂城為防堵詐騙氾濫、保障會員資金安全，在此提醒：信用卡、ATM轉帳、VIP專用帳戶存款等服務，務必使用「本人帳戶」！若使用非本人帳戶存款，將一律扣除處理費用後退還本金，感謝您的配合。    【維護公告】");
    document.writeln("                    親愛的會員您好，AV影城將於2020/12/14正式下架，造成不便敬請見諒。    【取款公告】");
    document.writeln("                    親愛的卡利會員您好，由於體育注單會因改判賽事等因素，而進行注單重新結算，因此即日起，卡利娛樂城進行出款時，體育相關注單須全數派彩完畢才處理支付款項，若玩家手上有未派彩注單，麻煩您耐心等候，如有相關疑問、歡迎諮詢24H線上客服，謝謝您。");
    document.writeln("                </marquee>");
    document.writeln("            </div>");
    document.writeln("        </div>");
    document.writeln("    </div>");
    document.writeln("</div>");
}

// PCFooter
function PCFooter() {
document.writeln("      <div class=\'container\'>");
document.writeln("        <div class=\'row\'>");
document.writeln("          <img src=\'../卡-img/桌機index_img/title6.png\' alt=\'\' class=\'py-3\'>");
document.writeln("          <div class=\'\' style=\'width: 14.2%;\'>");
document.writeln("            <p class=\'text-light text-center\' style=\'font-size: 1.2rem; border-bottom: #efe9e9 3px solid;\'>");
document.writeln("              真人娛樂</p>");
document.writeln("            <ul class=\'pt-3\'>");
document.writeln("              <li>");
document.writeln("                <a href=\'./page/LiveCasino.html\'>");
document.writeln("                  <p class=\'blog_tColor text-center\'>卡利百家樂</p>");
document.writeln("                </a>");
document.writeln("              </li>");
document.writeln("              <li>");
document.writeln("                <a href=\'./page/LiveCasino.html\'>");
document.writeln("                  <p class=\'blog_tColor text-center\'>歐博百家樂</p>");
document.writeln("                </a>");
document.writeln("              </li>");
document.writeln("              <li>");
document.writeln("                <a href=\'./page/LiveCasino.html\'>");
document.writeln("                  <p class=\'blog_tColor text-center\'>沙龍百家樂</p>");
document.writeln("                </a>");
document.writeln("              </li>");
document.writeln("              <li>");
document.writeln("                <a href=\'./page/LiveCasino.html\'>");
document.writeln("                  <p class=\'blog_tColor text-center\'>DG百家樂</p>");
document.writeln("                </a>");
document.writeln("              </li>");
document.writeln("              <li>");
document.writeln("                <a href=\'./page/LiveCasino.html\'>");
document.writeln("                  <p class=\'blog_tColor text-center\'>WM百家樂</p>");
document.writeln("                </a>");
document.writeln("              </li>");
document.writeln("            </ul>");
document.writeln("          </div>");
document.writeln("          <div class=\'\' style=\'width: 14.2%;\'>");
document.writeln("            <p class=\'text-light text-center\' style=\'font-size: 1.2rem; border-bottom: #efe9e9 3px solid;\'>");
document.writeln("              體育球版</p>");
document.writeln("            <ul class=\'pt-3\'>");
document.writeln("              <li>");
document.writeln("                <a href=\'./page/Sport.html\'>");
document.writeln("                  <p class=\'blog_tColor text-center\'>卡利體育</p>");
document.writeln("                </a>");
document.writeln("              </li>");
document.writeln("              <li>");
document.writeln("                <a href=\'./page/Sport.html\'>");
document.writeln("                  <p class=\'blog_tColor text-center\'>Super體育</p>");
document.writeln("                </a>");
document.writeln("              </li>");
document.writeln("            </ul>");
document.writeln("          </div>");
document.writeln("          <div class=\'\' style=\'width: 14.2%;\'>");
document.writeln("            <p class=\'text-light text-center\' style=\'font-size: 1.2rem; border-bottom: #efe9e9 3px solid;\'>");
document.writeln("              棋牌遊戲</p>");
document.writeln("            <ul class=\'pt-3\'>");
document.writeln("              <li>");
document.writeln("                <a href=\'./page/Chess.html\'>");
document.writeln("                  <p class=\'blog_tColor text-center\'>至尊棋牌</p>");
document.writeln("                </a>");
document.writeln("              </li>");
document.writeln("              <li>");
document.writeln("                <a href=\'./page/Chess.html\'>");
document.writeln("                  <p class=\'blog_tColor text-center\'>MG棋牌</p>");
document.writeln("                </a>");
document.writeln("              </li>");
document.writeln("            </ul>");
document.writeln("          </div>");
document.writeln("          <div class=\'\' style=\'width: 14.2%;\'>");
document.writeln("            <p class=\'text-light text-center\' style=\'font-size: 1.2rem; border-bottom: #efe9e9 3px solid;\'>");
document.writeln("              電子遊戯</p>");
document.writeln("            <ul class=\'pt-3\'>");
document.writeln("              <li>");
document.writeln("                <a href=\'./page/Slot.html\'>");
document.writeln("                  <p class=\'blog_tColor text-center\'>DT電子</p>");
document.writeln("                </a>");
document.writeln("              </li>");
document.writeln("              <li>");
document.writeln("                <a href=\'./page/Slot.html\'>");
document.writeln("                  <p class=\'blog_tColor text-center\'>RTG電子</p>");
document.writeln("                </a>");
document.writeln("              </li>");
document.writeln("              <li>");
document.writeln("                <a href=\'./page/Slot.html\'>");
document.writeln("                  <p class=\'blog_tColor text-center\'>SimplePlay</p>");
document.writeln("                </a>");
document.writeln("              </li>");
document.writeln("            </ul>");
document.writeln("          </div>");
document.writeln("          <div class=\'\' style=\'width: 14.2%;\'>");
document.writeln("            <p class=\'text-light text-center\' style=\'font-size: 1.2rem; border-bottom: #efe9e9 3px solid;\'>");
document.writeln("              賓果彩票</p>");
document.writeln("            <ul class=\'pt-3\'>");
document.writeln("              <li>");
document.writeln("                <a href=\'./page/Bingo.html\'>");
document.writeln("                  <p class=\'blog_tColor text-center\'>9K彩票</p>");
document.writeln("                </a>");
document.writeln("              </li>");
document.writeln("              <li>");
document.writeln("                <a href=\'./page/Bingo.html\'>");
document.writeln("                  <p class=\'blog_tColor text-center\'>六合彩</p>");
document.writeln("                </a>");
document.writeln("              </li>");
document.writeln("            </ul>");
document.writeln("          </div>");
document.writeln("          <div class=\'\' style=\'width: 14.2%;\'>");
document.writeln("            <p class=\'text-light text-center\' style=\'font-size: 1.2rem; border-bottom: #efe9e9 3px solid;\'>");
document.writeln("              捕魚王</p>");
document.writeln("            <ul class=\'pt-3\'>");
document.writeln("              <li>");
document.writeln("                <a href=\'./page/Fish.html\'>");
document.writeln("                  <p class=\'blog_tColor text-center\'>RTG電子</p>");
document.writeln("                </a>");
document.writeln("              </li>");
document.writeln("              <li>");
document.writeln("                <a href=\'./page/Fish.html\'>");
document.writeln("                  <p class=\'blog_tColor text-center\'>SimplePlay</p>");
document.writeln("                </a>");
document.writeln("              </li>");
document.writeln("            </ul>");
document.writeln("          </div>");
document.writeln("          <div class=\'\' style=\'width: 14.2%;\'>");
document.writeln("            <p class=\'text-light text-center\' style=\'font-size: 1.2rem; border-bottom: #efe9e9 3px solid;\'>");
document.writeln("              服務幫助</p>");
document.writeln("            <ul class=\'pt-3\'>");
document.writeln("              <li>");
document.writeln("                <a href=\'./header page/1AboutUs.html\'>");
document.writeln("                  <p class=\'blog_tColor text-center\'>關於我們</p>");
document.writeln("                </a>");
document.writeln("              </li>");
document.writeln("              <li>");
document.writeln("                <a href=\'./Features page/GameIntro.html\'>");
document.writeln("                  <p class=\'blog_tColor text-center\'>品牌介紹</p>");
document.writeln("                </a>");
document.writeln("              </li>");
document.writeln("              <li>");
document.writeln("                <a href=\'./Features page/CustomerService.html\'>");
document.writeln("                  <p class=\'blog_tColor text-center\'>客服中心</p>");
document.writeln("                </a>");
document.writeln("              </li>");
document.writeln("              <li>");
document.writeln("                <a href=\'./header page/3FAQ.html\'>");
document.writeln("                  <p class=\'blog_tColor text-center\'>公告專區</p>");
document.writeln("                </a>");
document.writeln("              </li>");
document.writeln("              <li>");
document.writeln("                <a href=\'./blog/AllBlog.html\'>");
document.writeln("                  <p class=\'blog_tColor text-center\'>部落格</p>");
document.writeln("                </a>");
document.writeln("              </li>");
document.writeln("              <li>");
document.writeln("                <a href=\'./header page/2AppDownload.html\'>");
document.writeln("                  <p class=\'blog_tColor text-center\'>app下載</p>");
document.writeln("                </a>");
document.writeln("              </li>");
document.writeln("              <li>");
document.writeln("                <a href=\'./header page/0Agent.html\'>");
document.writeln("                  <p class=\'blog_tColor text-center\'>合營代理</p>");
document.writeln("                </a>");
document.writeln("              </li>");
document.writeln("            </ul>");
document.writeln("          </div>");
document.writeln("          <!-- 合作品牌 -->");
document.writeln("          <div class=\'row\'>");
document.writeln("            <img src=\'../卡-img/桌機index_img/title7.png\' alt=\'\' class=\'py-2 pb-4\'>");
document.writeln("            <div class=\'col-12 px-6\' style=\'display: flex;justify-content: space-between;\'>");
document.writeln("              <div class=\'my-auto\'>");
document.writeln("                <img class=\'img-fluid\' style=\'width: 80px;\' src=\'../img/桌機index_img/各廠商/1-17.png\' alt=\'\'>");
document.writeln("              </div>");
document.writeln("              <div class=\'my-auto\'>");
document.writeln("                <img class=\'img-fluid\' style=\'width: 80px;\' src=\'../img/桌機index_img/各廠商/1-01.png\' alt=\'\'>");
document.writeln("              </div>");
document.writeln("              <div class=\'my-auto\'>");
document.writeln("                <img class=\'img-fluid\' style=\'width: 80px;\' src=\'../img/桌機index_img/各廠商/1-02.png\' alt=\'\'>");
document.writeln("              </div>");
document.writeln("              <div class=\'my-auto\'>");
document.writeln("                <img class=\'img-fluid\' style=\'width: 80px;\' src=\'../img/桌機index_img/各廠商/1-03.png\' alt=\'\'>");
document.writeln("              </div>");
document.writeln("              <div class=\'my-auto\'>");
document.writeln("                <img class=\'img-fluid\' style=\'width: 80px;\' src=\'../img/桌機index_img/各廠商/1-04.png\' alt=\'\'>");
document.writeln("              </div>");
document.writeln("              <div class=\'my-auto\'>");
document.writeln("                <img class=\'img-fluid\' style=\'width: 80px;\' src=\'../img/桌機index_img/各廠商/1-06.png\' alt=\'\'>");
document.writeln("              </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'col-12 pt-3 pb-4 px-7\' style=\'display: flex;justify-content: space-between;\'>");
document.writeln("              <div class=\'my-auto\'>");
document.writeln("                <img class=\'img-fluid\' style=\'width: 80px;\' src=\'../img/桌機index_img/各廠商/1-10.png\' alt=\'\'>");
document.writeln("              </div>");
document.writeln("              <div class=\'my-auto\'>");
document.writeln("                <img class=\'img-fluid\' style=\'width: 80px;\' src=\'../img/桌機index_img/各廠商/1-11.png\' alt=\'\'>");
document.writeln("              </div>");
document.writeln("              <div class=\'my-auto\'>");
document.writeln("                <img class=\'img-fluid\' style=\'width: 80px;\' src=\'../img/桌機index_img/各廠商/1-12.png\' alt=\'\'>");
document.writeln("              </div>");
document.writeln("              <div class=\'my-auto\'>");
document.writeln("                <img class=\'img-fluid\' style=\'width: 80px;\' src=\'../img/桌機index_img/各廠商/1-07.png\' alt=\'\'>");
document.writeln("              </div>");
document.writeln("              <div class=\'my-auto\'>");
document.writeln("                <img class=\'img-fluid\' style=\'width: 80px;\' src=\'../img/桌機index_img/各廠商/1-08.png\' alt=\'\'>");
document.writeln("              </div>");
document.writeln("              <div class=\'my-auto\'>");
document.writeln("                <img class=\'img-fluid\' style=\'width: 80px;\' src=\'../img/桌機index_img/各廠商/1-12.png\' alt=\'\'>");
document.writeln("              </div>");
document.writeln("              <div class=\'my-auto\'>");
document.writeln("                <img class=\'img-fluid\' style=\'width: 80px;\' src=\'../img/桌機index_img/各廠商/1-14.png\' alt=\'\'>");
document.writeln("              </div>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("          <!-- 國際 -->");
document.writeln("          <div class=\'row justify-content-center\'>");
document.writeln("            <img src=\'../卡-img/桌機index_img/title8.png\' alt=\'\' class=\'py-2 pb-4\'>");
document.writeln("            <div class=\'col-12 pt-3 px-7\' style=\'display: flex;justify-content: space-between;\'>");
document.writeln("              <div class=\'col my-auto\'>");
document.writeln("                <img src=\'../卡-img/桌機index_img/國際1.png\' alt=\'\'>");
document.writeln("              </div>");
document.writeln("              <div class=\'col my-auto\'>");
document.writeln("                <img src=\'../卡-img/桌機index_img/國際2.png\' alt=\'\'>");
document.writeln("              </div>");
document.writeln("              <div class=\'col my-auto\'>");
document.writeln("                <img src=\'../卡-img/桌機index_img/國際3.png\' alt=\'\'>");
document.writeln("              </div>");
document.writeln("              <div class=\'col my-auto\'>");
document.writeln("                <img src=\'../卡-img/桌機index_img/國際4.png\' alt=\'\'>");
document.writeln("              </div>");
document.writeln("              <div class=\'col my-auto\'>");
document.writeln("                <img src=\'../卡-img/桌機index_img/國際5.png\' alt=\'\'>");
document.writeln("              </div>");
document.writeln("              <div class=\'col my-auto\'>");
document.writeln("                <img src=\'../卡-img/桌機index_img/國際6.png\' alt=\'\'>");
document.writeln("              </div>");
document.writeln("              <div class=\'col my-auto\'>");
document.writeln("                <img src=\'../卡-img/桌機index_img/國際7.png\' alt=\'\'>");
document.writeln("              </div>");
document.writeln("              <div class=\'col my-auto\'>");
document.writeln("                <img src=\'../卡-img/桌機index_img/國際8.png\' alt=\'\'>");
document.writeln("              </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'col-12 py-2 mt-3\'>");
document.writeln("              <p class=\'text-center text-light\'>");
document.writeln("                <a href=\'./index.html\'>www.777vip.net</a>");
document.writeln("                Copyright© 2021 卡利. All Rights Reserved. 服務條款|隱私權保護政策");
document.writeln("              </p>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("        <!-- back-to-top -->");
document.writeln("        <button id=\'back-to-top\'");
document.writeln("          class=\'btn uk-position-fixed uk-position-bottom-right centerCenter d-none d-md-block rounded-circle\'");
document.writeln("          style=\'background-color: #7159f8; height: 2.8em;width: 2.8em;bottom: 2.5em;right: 2.5em;\'><i");
document.writeln("            class=\'fas fa-arrow-up text-light\'></i></button>");
document.writeln("        <!-- 滾動選軸 -->");
document.writeln("        <script>");
document.writeln("          $(document).ready(function () {");
document.writeln("            // 最上方隱藏");
document.writeln("            $(\'#back-to-top\').hide();");
document.writeln("            $(function () {");
document.writeln("              // 顯示");
document.writeln("              // $(window).scroll(function () {");
document.writeln("              //     if ($(window).scrollTop() > 30) {");
document.writeln("              //         $(\'#back-to-top\').fadeIn(1500);");
document.writeln("              //         $(\'#back-to-bottom\').fadeOut(1000);");
document.writeln("              //     } else {");
document.writeln("              //         $(\'#back-to-top\').fadeOut(1000);");
document.writeln("              //         $(\'#back-to-bottom\').fadeIn(1500);");
document.writeln("              //     }");
document.writeln("              // });");
document.writeln("              // 滾動");
document.writeln("              $(\'#back-to-top\').click(function () {");
document.writeln("                // 捲動最上面");
document.writeln("                $(\'body,html\').animate({");
document.writeln("                  scrollTop: 0");
document.writeln("                }, 1000);");
document.writeln("                // 捲動固定ID");
document.writeln("                // $(\'body,html\').animate({ scrollTop: $(\'#axc\').offset().top }, 1000);");
document.writeln("                return false;");
document.writeln("              });");
document.writeln("            });");
document.writeln("          });");
document.writeln("        </script>");
document.writeln("      </div>");
}

// MDFooter
function MDFooter() {
    document.writeln("<div class=\'container-fluid d-md-none p-0 m-0 fixed-bottom\'");
    document.writeln("    style=\'background: url(../卡-img/手機index_img/footer.png) no-repeat center; background-size: contain;\'>");
    document.writeln("    <div class=\'centerCenter\'>");
    document.writeln("      <!--  -->");
    document.writeln("      <a href=\'#modal-example2\' class=\'pr-4 text-light\' style=\'font-style: 24px;\' uk-toggle>");
    document.writeln("        <i class=\'fas fa-user\'");
    document.writeln("          style=\'font-size: 20px;\'> 登入</i>");
    document.writeln("      </a>");
    document.writeln("");
    document.writeln("      <div id=\'modal-example2\' class=\'uk-flex-top\' uk-modal>");
    document.writeln("        <div class=\'uk-modal-dialog uk-margin-auto-vertical w3-round-large\'>");
    document.writeln("          <div class=\'px-3 py-1 bgc-loginbar-color  row\' style=\' border-radius: 8px 8px 0 0;\'>");
    document.writeln("            <span class=\'pl-2 centerCenter font-weight-bold fsz-13\'>加入會員</span>");
    document.writeln("            <button class=\'uk-modal-close-default text-dark\' type=\'button\' uk-close></button>");
    document.writeln("          </div>");
    document.writeln("          <div class=\'text-secondary bg-theme px-5 pt-3 pb-5\'>");
    document.writeln("            <!--  -->");
    document.writeln("            <div class=\'row centerCenter p-1\'>");
    document.writeln("              <!-- 帳號 -->");
    document.writeln("              <div class=\'col-12 py-2 text-light\'>");
    document.writeln("                <i class=\'fas fa-user\'></i>");
    document.writeln("                <span class=\'pl-2\'>帳號</span>");
    document.writeln("              </div>");
    document.writeln("              <div class=\'col-12 py-2\'>");
    document.writeln("                <input type=\'text\'");
    document.writeln("                  class=\'w-100 px-3 py-1 text-secondary bg-theme border border-secondary w3-round-medium\'");
    document.writeln("                  placeholder=\'請輸入帳號\' onfocus=\'this.placeholder = \'\'\' onblur=\'this.placeholder = \'請輸入帳號\'\' />");
    document.writeln("              </div>");
    document.writeln("              <!-- 密碼 -->");
    document.writeln("              <div class=\'col-12 py-2 text-light\'>");
    document.writeln("                <i class=\'fas fa-unlock-alt\'></i>");
    document.writeln("                <span class=\'pl-2\'>密碼</span>");
    document.writeln("              </div>");
    document.writeln("              <div class=\'col-12 py-2\'>");
    document.writeln("                <input type=\'text\'");
    document.writeln("                  class=\'w-100 px-3 py-1 text-secondary bg-theme border border-secondary w3-round-medium\'");
    document.writeln("                  placeholder=\'請輸入正確密碼\' onfocus=\'this.placeholder = \'\'\' onblur=\'this.placeholder = \'請輸入正確密碼\'\' />");
    document.writeln("              </div>");
    document.writeln("");
    document.writeln("              <!-- 登入使用按鈕 -->");
    document.writeln("              <div class=\'col-12 px-2 pt-3\'>");
    document.writeln("                <div class=\'row centerCenter\'>");
    document.writeln("                  <a href=\'../page/indexLoginPage.html\'");
    document.writeln("                    class=\'col-12 my-1 btn w3-round-medium w3-medium font-weight-bold px-5 text-light bg-theme border border-danger lp1\'>立即註冊</a>");
    document.writeln("                  <a href=\'../loginPage/loginPage.html\'");
    document.writeln("                    class=\'col-12 my-1 btn w3-round-medium w3-medium font-weight-bold bgc-loginbar-color px-5 border-0 lp1\'>登入</a>");
    document.writeln("                </div>");
    document.writeln("              </div>");
    document.writeln("            </div>");
    document.writeln("          </div>");
    document.writeln("        </div>");
    document.writeln("      </div>");
    document.writeln("      <!--  -->");
    document.writeln("      <a href=\'/\'><img style=\'height: 57px;\' src=\'../卡-img/手機index_img/footer-home.png\' alt=\'\'></a>");
    document.writeln("      <!--  -->");
    document.writeln("      <a href=\'../page/indexLoginPage.html\' class=\'pl-4 text-light\' style=\'font-size: 24px;\'><i class=\'fas fa-user-plus\'");
    document.writeln("          style=\'font-size: 20px;\'></i> 註冊</a>");
    document.writeln("    </div>");
    document.writeln("  </div>");
}

// 登入頁面 Footer
function indexLoginFooter() {
    document.writeln("<div class=\'container-fluid d-md-none p-0 m-0 fixed-bottom\'");
    document.writeln("    style=\'background: url(../卡-img/手機index_img/footer.png) no-repeat center; background-size: contain;\'>");
    document.writeln("    <div class=\'centerCenter\'>");
    document.writeln("      <!--  -->");
    document.writeln("      <a href=\'#modal-example2\' class=\'pr-4 text-light\' style=\'font-style: 24px;\' uk-toggle>");
    document.writeln("        <i class=\'fas fa-user\'");
    document.writeln("          style=\'font-size: 20px;\'> 登入</i>");
    document.writeln("      </a>");
    document.writeln("");
    document.writeln("      <div id=\'modal-example2\' class=\'uk-flex-top\' uk-modal>");
    document.writeln("        <div class=\'uk-modal-dialog uk-margin-auto-vertical w3-round-large\'>");
    document.writeln("          <div class=\'px-3 py-1 bgc-loginbar-color  row\' style=\' border-radius: 8px 8px 0 0;\'>");
    document.writeln("            <span class=\'pl-2 centerCenter font-weight-bold fsz-13\'>加入會員</span>");
    document.writeln("            <button class=\'uk-modal-close-default text-dark\' type=\'button\' uk-close></button>");
    document.writeln("          </div>");
    document.writeln("          <div class=\'text-secondary bg-theme px-5 pt-3 pb-5\'>");
    document.writeln("            <!--  -->");
    document.writeln("            <div class=\'row centerCenter p-1\'>");
    document.writeln("              <!-- 帳號 -->");
    document.writeln("              <div class=\'col-12 py-2 text-light\'>");
    document.writeln("                <i class=\'fas fa-user\'></i>");
    document.writeln("                <span class=\'pl-2\'>帳號</span>");
    document.writeln("              </div>");
    document.writeln("              <div class=\'col-12 py-2\'>");
    document.writeln("                <input type=\'text\'");
    document.writeln("                  class=\'w-100 px-3 py-1 text-secondary bg-theme border border-secondary w3-round-medium\'");
    document.writeln("                  placeholder=\'請輸入帳號\' onfocus=\'this.placeholder = \'\'\' onblur=\'this.placeholder = \'請輸入帳號\'\' />");
    document.writeln("              </div>");
    document.writeln("              <!-- 密碼 -->");
    document.writeln("              <div class=\'col-12 py-2 text-light\'>");
    document.writeln("                <i class=\'fas fa-unlock-alt\'></i>");
    document.writeln("                <span class=\'pl-2\'>密碼</span>");
    document.writeln("              </div>");
    document.writeln("              <div class=\'col-12 py-2\'>");
    document.writeln("                <input type=\'text\'");
    document.writeln("                  class=\'w-100 px-3 py-1 text-secondary bg-theme border border-secondary w3-round-medium\'");
    document.writeln("                  placeholder=\'請輸入正確密碼\' onfocus=\'this.placeholder = \'\'\' onblur=\'this.placeholder = \'請輸入正確密碼\'\' />");
    document.writeln("              </div>");
    document.writeln("");
    document.writeln("              <!-- 登入使用按鈕 -->");
    document.writeln("              <div class=\'col-12 px-2 pt-3\'>");
    document.writeln("                <div class=\'row centerCenter\'>");
    document.writeln("                  <button");
    document.writeln("                    class=\'col-12 my-1 btn w3-round-medium w3-medium font-weight-bold px-5 text-light bg-theme border border-danger lp1\'>立即註冊</button>");
    document.writeln("                  <button");
    document.writeln("                    class=\'col-12 my-1 btn w3-round-medium w3-medium font-weight-bold bgc-loginbar-color px-5 border-0 lp1\'>登入</button>");
    document.writeln("                </div>");
    document.writeln("              </div>");
    document.writeln("            </div>");
    document.writeln("          </div>");
    document.writeln("        </div>");
    document.writeln("      </div>");
    document.writeln("      <!--  -->");
    document.writeln("      <a href=\'/\'><img style=\'height: 57px;\' src=\'../卡-img/手機index_img/footer-home.png\' alt=\'\'></a>");
    document.writeln("      <!--  -->");
    document.writeln("      <a href=\'/page/indexLoginPage.html\' class=\'pl-4 text-light\' style=\'font-size: 24px;\'><i class=\'fas fa-user-plus\'");
    document.writeln("          style=\'font-size: 20px;\'></i> 註冊</a>");
    document.writeln("    </div>");
    document.writeln("  </div><div class=\'container-fluid d-md-none p-0 m-0 fixed-bottom\'");
    document.writeln("        style=\'background: url(../卡-img/手機各分頁img/login/3.png) no-repeat center; background-size: cover;\'>");
    document.writeln("        <div class=\'centerCenter\'>");
    document.writeln("            <div class=\'row\'>");
    document.writeln("                <!-- 左 -->");
    document.writeln("                <div class=\'w-20 centerCenter\'>");
    document.writeln("                    <a href=\'../loginPage/1DepositWthdrawal.html\' class=\'\'>");
    document.writeln("                        <img class=\'w-100\' src=\'../卡-img/手機各分頁img/login/5.png\' alt=\'\'>");
    document.writeln("                    </a>");
    document.writeln("                </div><div class=\'w-20 centerCenter\'>");
    document.writeln("                    <a href=\'../loginPage/2EachStream.html\' class=\'\'>");
    document.writeln("                        <img class=\'w-100\' src=\'../卡-img/手機各分頁img/login/4.png\' alt=\'\'>");
    document.writeln("                    </a>");
    document.writeln("                </div>");
    document.writeln("                <!-- 中 -->");
    document.writeln("                <div class=\'w-20 centerCenter\'>");
    document.writeln("                    <a href=\'../index.html\' class=\'text-light\'>");
    document.writeln("                        <img src=\'../卡-img/手機index_img/footer-home.png\' alt=\'\'>");
    document.writeln("                    </a>");
    document.writeln("                </div>");
    document.writeln("                <!-- 右 -->");
    document.writeln("                <div class=\'w-20 centerCenter\'>");
    document.writeln("                    <a href=\'../page/Promotion.html\' class=\'\'>");
    document.writeln("                        <img class=\'w-100\' src=\'../卡-img/手機各分頁img/login/1.png\' alt=\'\'>");
    document.writeln("                    </a>");
    document.writeln("                </div>");
    document.writeln("                <div class=\'w-20 centerCenter pt-1\'>");
    document.writeln("                    <a href=\'../loginPage/loginPage.html\' class=\'\'>");
    document.writeln("                        <img class=\'w-100\' src=\'../卡-img/手機各分頁img/login/2.png\' alt=\'\'>");
    document.writeln("                    </a>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("        </div>");
    document.writeln("    </div>");
}

// 登入手機頁面 上方
function indexMDLoginHeader() {
    document.writeln("<div class=\'container-fluid d-md-none p-0 bgc-loginbar-color\'>");
    document.writeln("        <!-- 上條 -->");
    document.writeln("        <div class=\'slotBg row p-0 py-2\'>");
    document.writeln("            <!--  -->");
    document.writeln("            <div class=\'col-4 p-0 pl-2 my-auto\'>");
    document.writeln("                <button class=\'btn py-0\' type=\'button\' onclick=\'history.back()\' value=\'回到上一頁\'>");
    document.writeln("                    <i class=\'fas fa-angle-left text-theme fa-lg\'></i>");
    document.writeln("                </button>");
    document.writeln("            </div>");
    document.writeln("            <!--  -->");
    document.writeln("            <div class=\'col-4 p-0 centerCenter\'>");
    document.writeln("                <li class=\'breadcrumb-item active\' aria-current=\'page\'>");
    document.writeln("                    <span class=\'pl-2 text-theme\' style=\'font-size: 23px;\' id=\'copyTitle\'></span>");
    document.writeln("                </li>");
    document.writeln("                <script>");
    document.writeln("                    $(document).ready(function () {");
    document.writeln("                        let title = $(\'title\').text();");
    document.writeln("                        $(\'#copyTitle\').html(title);");
    document.writeln("                    });");
    document.writeln("                </script>");
    document.writeln("            </div>");
    document.writeln("            <!-- 24HR客服 -->");
    document.writeln("            <div class=\'col-4 p-0 centerCenter text-theme\'>");
    document.writeln("                <img id=\'hrServiceBtn\' src=\'../卡-img/手機index_img/24h.png\' alt=\'\' class=\'img-fluid\' data-toggle=\'modal\'");
    document.writeln("                    data-target=\'#exampleModal\'>");
    document.writeln("                <!-- 24HR客服 Modal -->");
    document.writeln("                <div class=\'modal fade\' id=\'exampleModal\' tabindex=\'-1\' role=\'dialog\'");
    document.writeln("                    aria-labelledby=\'exampleModalLabel\' aria-hidden=\'true\'>");
    document.writeln("                    <div class=\'modal-dialog\' role=\'document\'>");
    document.writeln("                        <div class=\'modal-content mx-auto w-75\'");
    document.writeln("                            style=\'position: fixed !important;top: 6% !important; left: 10% !important;right: 10% !important;\'>");
    document.writeln("                            <!-- 聯繫我們 -->");
    document.writeln("                            <div class=\'modal-header bgc-header-color\'>");
    document.writeln("                                <p class=\'modal-title m-auto w3-text-white\' id=\'exampleModalLabel\'");
    document.writeln("                                    style=\'font-size: 1.2rem !important;\'>聯繫我們");
    document.writeln("                                </p>");
    document.writeln("                            </div>");
    document.writeln("                            <!-- img -->");
    document.writeln("                            <div class=\'modal-body p-0\'>");
    document.writeln("                                <img src=\'../卡-img/手機index_img/24x7.png\' alt=\'\' class=\'w-100\'>");
    document.writeln("                            </div>");
    document.writeln("                            <!-- Close -->");
    document.writeln("                            <div class=\'w-100 bgc-header-color\'>");
    document.writeln("                                <div class=\'py-2 text-center w3-text-white\' style=\'cursor: pointer;\'");
    document.writeln("                                    data-dismiss=\'modal\'>Close</div>");
    document.writeln("                            </div>");
    document.writeln("                        </div>");
    document.writeln("                    </div>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("            <style>");
    document.writeln("                .modal-backdrop.show {");
    document.writeln("                    z-index: -1;");
    document.writeln("                }");
    document.writeln("            </style>");
    document.writeln("        </div>");
    document.writeln("        <!-- 下條 -->");
    document.writeln("        <div class=\'row p-0 py-2\'>");
    document.writeln("            <div class=\'col-6 p-0 centerCenter\'>");
    document.writeln("                <div class=\'list-inline-item centerCenter\'>");
    document.writeln("                    <span class=\'\'>會員</span>");
    document.writeln("                    <span>4141563</span>");
    document.writeln("                </div>");
    document.writeln("                <div class=\'list-inline-item centerCenter\'>");
    document.writeln("                    <img style=\'width: 10%;\' src=\'../卡-img/桌機各分頁img/indexLogin_登入條/1.png\' alt=\'\'>");
    document.writeln("                    <img style=\'width: 10%;\' src=\'../卡-img/桌機各分頁img/indexLogin_登入條/2.png\' alt=\'\'>");
    document.writeln("                    <img style=\'width: 10%;\' src=\'../卡-img/桌機各分頁img/indexLogin_登入條/2.png\' alt=\'\'>");
    document.writeln("                    <img style=\'width: 10%;\' src=\'../卡-img/桌機各分頁img/indexLogin_登入條/2.png\' alt=\'\'>");
    document.writeln("                    <img style=\'width: 10%;\' src=\'../卡-img/桌機各分頁img/indexLogin_登入條/2.png\' alt=\'\'>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("            <div class=\'col-6 p-0 centerCenter\'>");
    document.writeln("                <img class=\'img-fluid\' src=\'../卡-img/桌機各分頁img/indexLogin_登入條/money.png\' alt=\'\'>");
    document.writeln("                <span class=\'pl-2\'>9,000.00</span>");
    document.writeln("                <button class=\'btn p-0 m-0\'>");
    document.writeln("                    <img class=\'img-fluid pl-2\' src=\'../卡-img/桌機各分頁img/indexLogin_登入條/4.png\' alt=\'\'>");
    document.writeln("                </button>");
    document.writeln("            </div>");
    document.writeln("        </div>");
    document.writeln("    </div>");
}

// 登入頁面 上方
function indexLoginHeader() {
    document.writeln("<div class=\'container-fluid d-none d-md-block p-0 bgc-loginbar-color\'>");
    document.writeln("        <div class=\'container\'>");
    document.writeln("            <div class=\'row py-2\'>");
    document.writeln("                <div class=\'col-6 centerCenter\'>");
    document.writeln("                    <div class=\'list-inline-item pl-2\'>");
    document.writeln("                        <img class=\'img-fluid\' src=\'../卡-img/桌機各分頁img/indexLogin_登入條/1.png\' alt=\'\'>");
    document.writeln("                        <img class=\'img-fluid\' src=\'../卡-img/桌機各分頁img/indexLogin_登入條/2.png\' alt=\'\'>");
    document.writeln("                        <img class=\'img-fluid\' src=\'../卡-img/桌機各分頁img/indexLogin_登入條/2.png\' alt=\'\'>");
    document.writeln("                        <img class=\'img-fluid\' src=\'../卡-img/桌機各分頁img/indexLogin_登入條/2.png\' alt=\'\'>");
    document.writeln("                        <img class=\'img-fluid\' src=\'../卡-img/桌機各分頁img/indexLogin_登入條/2.png\' alt=\'\'>");
    document.writeln("                        <span class=\'pl-2\'>會員</span>");
    document.writeln("                        <span>4141563</span>");
    document.writeln("                        <img class=\'img-fluid pl-4\' src=\'../卡-img/桌機各分頁img/indexLogin_登入條/money.png\' alt=\'\'>");
    document.writeln("                        <span>9,000.00</span>");
    document.writeln("                        <button class=\'btn p-0 m-0\'>");
    document.writeln("                            <img class=\'img-fluid pl-1\' src=\'../卡-img/桌機各分頁img/indexLogin_登入條/4.png\' alt=\'\'>");
    document.writeln("                        </button>");
    document.writeln("                    </div>");
    document.writeln("                </div>");
    document.writeln("                <div class=\'col-6 centerCenter list-inline fsz-08\'>");
    document.writeln("                    <!-- 1.我的錢包 -->");
    document.writeln("                    <a href=\'./MyPurse.html\' class=\'btn list-inline-item p-1 w3-hover-shadow\'>");
    document.writeln("                        <li class=\'text-center\'><img src=\'../卡-img/桌機各分頁img/indexLogin_登入條/bt1.png\' alt=\'\'>");
    document.writeln("                        </li>");
    document.writeln("                        <p class=\'text-dark font-weight-bold\'>我的錢包</p>");
    document.writeln("                    </a>");
    document.writeln("                    <!-- 2.存取流程 -->");
    document.writeln("                    <a href=\'../Features page/AccessFlow.html\' class=\'btn list-inline-item p-1 w3-hover-shadow\'>");
    document.writeln("                        <li class=\'text-center\'><img src=\'../卡-img/桌機各分頁img/indexLogin_登入條/bt2.png\' alt=\'\'>");
    document.writeln("                        </li>");
    document.writeln("                        <p class=\'text-dark font-weight-bold\'>存取流程</p>");
    document.writeln("                    </a>");
    document.writeln("                    <!-- 3.會員通知 -->");
    document.writeln("                    <a href=\'#modal-example1\' class=\'btn list-inline-item p-1 w3-hover-shadow\' uk-toggle>");
    document.writeln("                        <li class=\'text-center\'>");
    document.writeln("                            <img src=\'../卡-img/桌機各分頁img/indexLogin_登入條/bt7.png\' alt=\'\'>");
    document.writeln("                        </li>");
    document.writeln("                        <p class=\'text-dark font-weight-bold\'>會員通知</p>");
    document.writeln("                    </a>");
    document.writeln("");
    document.writeln("                    <div id=\'modal-example1\' uk-modal>");
    document.writeln("                        <div class=\'uk-modal-dialog w3-round-large\'>");
    document.writeln("                            <div class=\'px-3 py-1 bgc-loginbar-color\' style=\'border-radius: 8px 8px 0  0;\'>");
    document.writeln("                                <i class=\'far fa-bell\'></i>");
    document.writeln("                                <span class=\'pl-2\'>會員通知</span>");
    document.writeln("                                <button class=\'uk-modal-close-default text-dark\' type=\'button\' uk-close></button>");
    document.writeln("                            </div>");
    document.writeln("                            <div class=\'text-secondary bg-theme px-5 pt-3 pb-5\'>");
    document.writeln("                                <!--  -->");
    document.writeln("                                <p class=\'text-center py-1\'>公告專區</p>");
    document.writeln("                                <!--  -->");
    document.writeln("                                <ul uk-accordion=\'\' class=\'uk-accordion\'>");
    document.writeln("                                    <!-- 1 -->");
    document.writeln("                                    <li class=\'uk-open\'>");
    document.writeln("                                        <a class=\'uk-accordion-title fsz-1 text-secondary\' href=\'#\'>【標題】存款公告</a>");
    document.writeln("                                        <div class=\'uk-accordion-content\'>");
    document.writeln("                                            <p class=\'fsz-08 text-secondary\'>1. 一般存款沒有享受任何優惠的情況下，達到1倍流水即可出款");
    document.writeln("                                                <br>");
    document.writeln("                                                2. 一週三次，一天最多一次免手續費，每日超過免費次數，收取1%、2%手續費…最高5%");
    document.writeln("                                            </p>");
    document.writeln("                                        </div>");
    document.writeln("                                    </li>");
    document.writeln("                                    <!-- 2 -->");
    document.writeln("                                    <li>");
    document.writeln("                                        <a class=\'uk-accordion-title fsz-1 text-secondary\' href=\'#\'>【標題】存款公告</a>");
    document.writeln("                                        <div class=\'uk-accordion-content\' hidden=\'\'>");
    document.writeln("                                            <p class=\'fsz-08 text-secondary\'>");
    document.writeln("                                                1. 一般存款沒有享受任何優惠的情況下，達到1倍流水即可出款");
    document.writeln("                                                <br>");
    document.writeln("                                                2. 一週三次，一天最多一次免手續費，每日超過免費次數，收取1%、2%手續費…最高5%");
    document.writeln("                                            </p>");
    document.writeln("                                        </div>");
    document.writeln("                                    </li>");
    document.writeln("                                </ul>");
    document.writeln("                            </div>");
    document.writeln("                        </div>");
    document.writeln("                    </div>");
    document.writeln("                    <!-- 5.btn -->");
    document.writeln("                    <a href=\'../index.html\' class=\'btn p-0 m-0 \'>");
    document.writeln("                        <img src=\'../卡-img/桌機各分頁img/indexLogin_登入條/登出.png\' alt=\'\' class=\'img-fluid\'>");
    document.writeln("                    </a>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("        </div>");
    document.writeln("    </div>");
}
