// page頁面 上方
function PageHeader() {
    document.writeln("<!-- 電腦板 header ------------------------------------------------------------------------>");
    document.writeln("            <!-- login ------------------------------------>");
    document.writeln("            <div class=\'container-fluid d-none d-md-block p-0 bgc-header-color\'>");
    document.writeln("                <div class=\'container\'>");
    document.writeln("                    <div class=\'row py-2\'>");
    document.writeln("                        <div class=\'col-12 text-right\'>");
    document.writeln("                            <!-- 帳號 -->");
    document.writeln("                            <input type=\'text\' class=\'px-2 input-style\' style=\'background-color: #efbe6c;\' placeholder=\'用戶名(ID)\'");
    document.writeln("                                onfocus=\'this.placeholder = \'\'\' onblur=\'this.placeholder = \' 用戶名(ID)\'\' />");
    document.writeln("                            <!-- 密碼 -->");
    document.writeln("                            <input type=\'password\' class=\'px-2 input-style\' style=\'background-color: #7dd2e8;\' placeholder=\'密碼\'");
    document.writeln("                                onfocus=\'this.placeholder = \'\'\' onblur=\'this.placeholder = \' 密碼\'\' />");
    document.writeln("                            <!-- 記住 -->");
    document.writeln("                            <input class=\'ml-2\' type=\'checkbox\' name=\'記住\' id=\'\'>");
    document.writeln("                            <p class=\'d-inline\'>記住</p>");
    document.writeln("                            <!-- 登入 -->");
    document.writeln("                            <a href=\'../page/indexLogin.html\'><input class=\'input-size ml-2 text-center\'");
    document.writeln("                                    style=\'background-image: url(../img/桌機index_img/btn登入.png);color: #efbe6c;\' type=\'submit\'");
    document.writeln("                                    value=\'登入\'></a>");
    document.writeln("                            <a href=\'../header page/Signup.html\'><input class=\'input-size ml-2 text-center\'");
    document.writeln("                                    style=\'background-image: url(../img/桌機index_img/btn注冊.png);color: #fd788e;\' type=\'button\'");
    document.writeln("                                    value=\'註冊\'></a>");
    document.writeln("                        </div>");
    document.writeln("                    </div>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("        ");
    document.writeln("            <!-- LG Navigation Bars ------------------------------------>");
    document.writeln("            <div class=\'container-fluid d-none d-lg-block p-0 bgc-header-color NavigationBorder\'>");
    document.writeln("                <div class=\'container\'>");
    document.writeln("                    <div class=\'row\' style=\'align-items:center;\'>");
    document.writeln("                        <div class=\'col-3\'>");
    document.writeln("<a class=\'\' href=\'../index.html\'><img class=\'\' style=\'width: 60%;\' src=\'/123ts/img/手機index_img/派大金LOGO2.png\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col-9\'>");
    document.writeln("                            <div class=\'row mx-auto\'>");
    document.writeln("                                <a class=\'col py-2 centerCenter listHove\' href=\'../page/LiveCasino.html\'><img class=\'img-fluid\'");
    document.writeln("                                        src=\'../img/桌機index_img/list1.png\' alt=\'\'></a>");
    document.writeln("                                <a class=\'col py-2 centerCenter listHove\' href=\'../page/Sport.html\'><img class=\'img-fluid\'");
    document.writeln("                                        src=\'../img/桌機index_img/list2.png\' alt=\'\'></a>");
    document.writeln("                                <a class=\'col py-2 centerCenter listHove\' href=\'../page/Slot.html\'><img class=\'img-fluid\'");
    document.writeln("                                        src=\'../img/桌機index_img/list3.png\' alt=\'\'></a>");
    document.writeln("                                <a class=\'col py-2 centerCenter listHove\' href=\'../page/Bingo.html\'><img class=\'img-fluid\'");
    document.writeln("                                        src=\'../img/桌機index_img/list4.png\' alt=\'\'></a>");
    document.writeln("                                <a class=\'col py-2 centerCenter listHove\' href=\'../page/Fish.html\'><img class=\'img-fluid\'");
    document.writeln("                                        src=\'../img/桌機index_img/list5.png\' alt=\'\'></a>");
    document.writeln("                                <a class=\'col py-2 centerCenter listHove\' href=\'../page/Chess.html\'><img class=\'img-fluid\'");
    document.writeln("                                        src=\'../img/桌機index_img/list6.png\' alt=\'\'></a>");
    document.writeln("                                <a class=\'col py-2 centerCenter listHove\' href=\'../page/Movie.html\'><img class=\'img-fluid\'");
    document.writeln("                                        src=\'../img/桌機index_img/list7.png\' alt=\'\'></a>");
    document.writeln("                                <a class=\'col py-2 centerCenter listHove\' href=\'../page/Promotion.html\'><img class=\'img-fluid\'");
    document.writeln("                                        src=\'../img/桌機index_img/list8.png\' alt=\'\'></a>");
    document.writeln("                            </div>");
    document.writeln("                        </div>");
    document.writeln("                    </div>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("        ");
    document.writeln("            <!-- 維護時間 -->");
    document.writeln("            <div class=\'dropleft d-none d-md-block position-absolute\'>");
    document.writeln("                <!-- BMaintenanceTime 控制項 -->");
    document.writeln("                <a class=\'btn BMaintenanceTime p-0\' data-toggle=\'dropdown\' aria-haspopup=\'true\' aria-expanded=\'false\'");
    document.writeln("                    id=\'dropdownMenuReference\'><img src=\'../img/桌機index_img/LeftSidebar.png\' class=\'img-fluid p-0 m-0\'");
    document.writeln("                        alt=\'\'></a>");
    document.writeln("                <div class=\'dropdown-menu px-3 bgc-header-color\' aria-labelledby=\'dropdownMenuReference\'");
    document.writeln("                    style=\'height: 300px; overflow: scroll;overflow-x: hidden;\'>");
    document.writeln("                    <div class=\'pt-3\'>");
    document.writeln("                        <p class=\'text-center\'>緊急維修</p>");
    document.writeln("                        <p class=\'text-light text-center bg-i-purple\'>幸運棋牌</p>");
    document.writeln("                        <p class=\'text-center\'>01/12/2020 02:00:00</p>");
    document.writeln("                    </div>");
    document.writeln("                    <div class=\'pt-3\'>");
    document.writeln("                        <p class=\'text-center\' style=\'height: 1px;width: 100%;background: #555;\'></p>");
    document.writeln("                    </div>");
    document.writeln("                    <div class=\'pt-3\'>");
    document.writeln("                        <p class=\'text-center\'>星期一</p>");
    document.writeln("                        <p class=\'text-light text-center bg-i-purple\'>9K彩票</p>");
    document.writeln("                        <p class=\'text-center\'>00:00 至 00:00</p>");
    document.writeln("                    </div>");
    document.writeln("                    <div class=\'pt-3\'>");
    document.writeln("                        <p class=\'text-light text-center bg-i-purple\'>Super體育</p>");
    document.writeln("                        <p class=\'text-center\'>12:30 至 16:00</p>");
    document.writeln("                    </div>");
    document.writeln("                    <div class=\'pt-3\'>");
    document.writeln("                        <p class=\'text-light text-center bg-i-purple\'>WM百家樂</p>");
    document.writeln("                        <p class=\'text-center\'>12:00 至 14:30</p>");
    document.writeln("                    </div>");
    document.writeln("                    <div class=\'pt-3\'>");
    document.writeln("                        <p class=\'text-light text-center bg-i-purple\'>任你博體育</p>");
    document.writeln("                        <p class=\'text-center\'>16:00 至 18:00</p>");
    document.writeln("                    </div>");
    document.writeln("                    <div class=\'pt-3\'>");
    document.writeln("                        <p class=\'text-light text-center bg-i-purple\'>六合彩539</p>");
    document.writeln("                        <p class=\'text-center\'>12:30 至 16:30</p>");
    document.writeln("                    </div>");
    document.writeln("                    <div class=\'pt-3\'>");
    document.writeln("                        <p class=\'text-light text-center bg-i-purple\'>幸運棋牌</p>");
    document.writeln("                        <p class=\'text-center\'>23:00 至 00:00</p>");
    document.writeln("                    </div>");
    document.writeln("                    <div class=\'pt-3\'>");
    document.writeln("                        <p class=\'text-light text-center bg-i-purple\'>歐博百家樂</p>");
    document.writeln("                        <p class=\'text-center\'>08:00 至 12:00</p>");
    document.writeln("                    </div>");
    document.writeln("                    <div class=\'pt-3\'>");
    document.writeln("                        <p class=\'text-light text-center bg-i-purple\'>沙龍百家樂</p>");
    document.writeln("                        <p class=\'text-center\'>10:00 至 12:30</p>");
    document.writeln("                    </div>");
    document.writeln("                    <div class=\'pt-3\'>");
    document.writeln("                        <p class=\'text-center\' style=\'height: 1px;width: 100%;background: #555;\'></p>");
    document.writeln("                    </div>");
    document.writeln("                    <div class=\'pt-3\'>");
    document.writeln("                        <p class=\'text-center\'>星期二</p>");
    document.writeln("                        <p class=\'text-light text-center bg-i-purple\'>RTG電子</p>");
    document.writeln("                        <p class=\'text-center\'>07:00 至 09:00</p>");
    document.writeln("                    </div>");
    document.writeln("                    <div class=\'pt-3\'>");
    document.writeln("                        <p class=\'text-center\' style=\'height: 1px;width: 100%;background: #555;\'></p>");
    document.writeln("                    </div>");
    document.writeln("                    <div class=\'pt-3\'>");
    document.writeln("                        <p class=\'text-center\'>星期三</p>");
    document.writeln("                        <p class=\'text-light text-center bg-i-purple\'>DG電子</p>");
    document.writeln("                        <p class=\'text-center\'>07:00 至 10:00</p>");
    document.writeln("                    </div>");
    document.writeln("                    <div class=\'pt-3\'>");
    document.writeln("                        <p class=\'text-light text-center bg-i-purple\'>MG棋牌</p>");
    document.writeln("                        <p class=\'text-center\'>11:00 至 13:00</p>");
    document.writeln("                    </div>");
    document.writeln("                    <div class=\'pt-3\'>");
    document.writeln("                        <p class=\'text-center\' style=\'height: 1px;width: 100%;background: #555;\'></p>");
    document.writeln("                    </div>");
    document.writeln("                    <div class=\'pt-3\'>");
    document.writeln("                        <p class=\'text-center\'>星期四</p>");
    document.writeln("                        <p class=\'text-light text-center bg-i-purple\'>SimplePlay電子</p>");
    document.writeln("                        <p class=\'text-center\'>11:00 至 13:30</p>");
    document.writeln("                    </div>");
    document.writeln("                    <div class=\'pt-3\'>");
    document.writeln("                        <p class=\'text-center\' style=\'height: 1px;width: 100%;background: #555;\'></p>");
    document.writeln("                    </div>");
    document.writeln("                    <div class=\'pt-3\'>");
    document.writeln("                        <p class=\'text-center\'>星期五</p>");
    document.writeln("                        <p class=\'text-light text-center bg-i-purple\'>SimplePlay電子</p>");
    document.writeln("                        <p class=\'text-center\'>15:00 至 19:00</p>");
    document.writeln("                    </div>");
    document.writeln("                    <div class=\'pt-3\'>");
    document.writeln("                        <p class=\'text-center\' style=\'height: 1px;width: 100%;background: #555;\'></p>");
    document.writeln("                    </div>");
    document.writeln("                    <div class=\'py-3\'>");
    document.writeln("                        <p class=\'text-center\'>星期日</p>");
    document.writeln("                        <p class=\'text-light text-center bg-i-purple\'>BNG電子</p>");
    document.writeln("                        <p class=\'text-center\'>14:30 至 02:30</p>");
    document.writeln("                    </div>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("        ");
    document.writeln("        ");
    document.writeln("            <!-- 聯繫我們 -->");
    document.writeln("            <div class=\'d-none d-md-block\'>");
    document.writeln("                <div class=\'contactUs p-1 rounded-right w3-round-large\'>");
    document.writeln("                    <!-- 1 -->");
    document.writeln("                    <a href=\'https://line.me/R/ti/p/%40661quprf\' class=\'btn px-0 pt-1 pb-3 m-0 bg-cover border-bottom\'");
    document.writeln("                        target=\'_blank\'>");
    document.writeln("                        <img src=\'../img/桌機index_img/RightSidebar.png\' class=\'img-fluid\' alt=\'\'>");
    document.writeln("                    </a>");
    document.writeln("                    <!-- 2 -->");
    document.writeln("                    <a href=\'#modal-example\' class=\'btn px-1 pt-2 pb-1 m-0 bg-cover\' uk-toggle>");
    document.writeln("                        <img class=\'img-fluid\' src=\'../img/桌機index_img/RightSidebar2.png\' alt=\'\'>");
    document.writeln("                    </a>");
    document.writeln("                    <!-- 2 modal -->");
    document.writeln("                    <div id=\'modal-example\' uk-modal>");
    document.writeln("                        <div class=\'uk-modal-dialog uk-modal-body\' style=\'background-color: rgba(185, 101, 146, 0.9);\'>");
    document.writeln("                            <h2 class=\'uk-modal-title text-light\'>意見反饋</h2>");
    document.writeln("                            <!-- table -->");
    document.writeln("                            <table class=\'uk-table text-light\'>");
    document.writeln("                                <thead>");
    document.writeln("                                    <tr>");
    document.writeln("                                        <th class=\'text-light\'></th>");
    document.writeln("                                        <th class=\'text-light\'>極差</th>");
    document.writeln("                                        <th class=\'text-light\'>很差</th>");
    document.writeln("                                        <th class=\'text-light\'>普通</th>");
    document.writeln("                                        <th class=\'text-light\'>很好</th>");
    document.writeln("                                        <th class=\'text-light\'>極好</th>");
    document.writeln("                                    </tr>");
    document.writeln("                                </thead>");
    document.writeln("                                <tbody>");
    document.writeln("                                    <tr>");
    document.writeln("                                        <td>客服服務</td>");
    document.writeln("                                        <td><input type=\'radio\' name=\'1\' id=\'\'></td>");
    document.writeln("                                        <td><input type=\'radio\' name=\'1\' id=\'\'></td>");
    document.writeln("                                        <td><input type=\'radio\' name=\'1\' id=\'\'></td>");
    document.writeln("                                        <td><input type=\'radio\' name=\'1\' id=\'\'></td>");
    document.writeln("                                        <td><input type=\'radio\' name=\'1\' id=\'\'></td>");
    document.writeln("                                    </tr>");
    document.writeln("                                    <tr>");
    document.writeln("                                        <td>提款速度</td>");
    document.writeln("                                        <td><input type=\'radio\' name=\'2\' id=\'\'></td>");
    document.writeln("                                        <td><input type=\'radio\' name=\'2\' id=\'\'></td>");
    document.writeln("                                        <td><input type=\'radio\' name=\'2\' id=\'\'></td>");
    document.writeln("                                        <td><input type=\'radio\' name=\'2\' id=\'\'></td>");
    document.writeln("                                        <td><input type=\'radio\' name=\'2\' id=\'\'></td>");
    document.writeln("                                    </tr>");
    document.writeln("                                    <tr>");
    document.writeln("                                        <td>操作界面</td>");
    document.writeln("                                        <td><input type=\'radio\' name=\'3\' id=\'\'></td>");
    document.writeln("                                        <td><input type=\'radio\' name=\'3\' id=\'\'></td>");
    document.writeln("                                        <td><input type=\'radio\' name=\'3\' id=\'\'></td>");
    document.writeln("                                        <td><input type=\'radio\' name=\'3\' id=\'\'></td>");
    document.writeln("                                        <td><input type=\'radio\' name=\'3\' id=\'\'></td>");
    document.writeln("                                    </tr>");
    document.writeln("                                    <tr>");
    document.writeln("                                        <td>網路連結速度</td>");
    document.writeln("                                        <td><input type=\'radio\' name=\'4\' id=\'\'></td>");
    document.writeln("                                        <td><input type=\'radio\' name=\'4\' id=\'\'></td>");
    document.writeln("                                        <td><input type=\'radio\' name=\'4\' id=\'\'></td>");
    document.writeln("                                        <td><input type=\'radio\' name=\'4\' id=\'\'></td>");
    document.writeln("                                        <td><input type=\'radio\' name=\'4\' id=\'\'></td>");
    document.writeln("                                    </tr>");
    document.writeln("                                </tbody>");
    document.writeln("                            </table>");
    document.writeln("                            <div class=\'row pb-3\'>");
    document.writeln("                                <div class=\'col-3 text-light ml-3\'>意見</div>");
    document.writeln("                                <div class=\'flex-grow-1\'>");
    document.writeln("                                    <textarea name=\'\' id=\'\' cols=\'39\' rows=\'5\'></textarea>");
    document.writeln("                                </div>");
    document.writeln("                            </div>");
    document.writeln("                            <p class=\'uk-text-right\'>");
    document.writeln("                                <button class=\'uk-button bg-i-purple text-light\' type=\'button\'>提交</button>");
    document.writeln("                            </p>");
    document.writeln("                        </div>");
    document.writeln("                    </div>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("        ");
    document.writeln("            <!-- 手機板 header ------------------------------------------------------------------------>");
    document.writeln("            <!-- MD Navigation Bars ------------------------------------>");
    document.writeln("            <div class=\'container-fluid p-0 d-lg-none bgc-header-color MdNavigationBorder\'>");
    document.writeln("                <div class=\'container\'>");
    document.writeln("                    <div class=\'row py-2\' style=\'align-items: center;\'>");
    document.writeln("                        <!-- 漢堡圖 -->");
    document.writeln("                        <div class=\'col-4 text-left\'>");
    document.writeln("                            <!-- HamburgBtn -->");
    document.writeln("                            <i class=\'fas fa-bars fa-2x\' style=\'color: #fb98ac;\' id=\'HamburgBtn\' data-toggle=\'modal\'");
    document.writeln("                                data-target=\'#exampleModal0\'></i>");
    document.writeln("                            <!-- HamburgBtn modal -->");
    document.writeln("                            <div class=\'modal\' id=\'exampleModal0\'>");
    document.writeln("                                <div id=\'showMenu p-0\' class=\'modal-dialog\'>");
    document.writeln("                                    <div class=\'showMenuList modal-content\'>");
    document.writeln("                                        <div class=\'modal-body p-0 m-0\'>");
    document.writeln("                                            <!-- 關閉 -->");
    document.writeln("                                            <!-- <div class=\'w-100\'>");
    document.writeln("                                                                    <div class=\'pb-2 pt-1 pr-3 text-light text-right\' data-dismiss=\'modal\'><i");
    document.writeln("                                                                            class=\'fas fa-times text-light\'></i></div>");
    document.writeln("                                                                </div> -->");
    document.writeln("                                            <!-- 派大金logo -->");
    document.writeln("                                            <div class=\'row m-0 px-5 py-3 bgc-body-color hamburg-border-bottom\'");
    document.writeln("                                                style=\'box-shadow: 0 1px 5px rgba(83, 83, 83, 0.041);\'>");
    document.writeln("                                                <img class=\'centerCenter img-fluid\' src=\'/123ts/img/手機index_img/派大金LOGO2.png\'");
    document.writeln("                                                    alt=\'\'>");
    document.writeln("                                            </div>");
    document.writeln("                                            <!-- 首頁 -->");
    document.writeln("                                            <div class=\'row clearfix m-0\'>");
    document.writeln("                                                <div class=\'col-12 p-3 hamburg-border-bottom w-100\'>");
    document.writeln("                                                    <a class=\'py-3 pl-1 text-decoration-none\' href=\'../index.html\'>");
    document.writeln("                                                        <img class=\'img-fluid pl-3\' src=\'../img/手機index_img/icon1-home.png\'");
    document.writeln("                                                            alt=\'\'>");
    document.writeln("                                                        <span class=\'pl-3 h5\' style=\'color: #fb98ac;\'>首頁</span>");
    document.writeln("                                                        <div class=\'float-right\'><i class=\'fas fa-angle-right\'");
    document.writeln("                                                                style=\'color: #fb98ac;\'></i></div>");
    document.writeln("                                                    </a>");
    document.writeln("                                                </div>");
    document.writeln("                                            </div>");
    document.writeln("                                            <!-- 優惠活動 -->");
    document.writeln("                                            <div class=\'row clearfix m-0\'>");
    document.writeln("                                                <div class=\'col-12 p-3 hamburg-border-bottom w-100\'>");
    document.writeln("                                                    <a class=\'py-3 pl-1 text-decoration-none\' href=\'../page/Promotion.html\'>");
    document.writeln("                                                        <img class=\'img-fluid pl-3\' src=\'../img/手機index_img/icon2-promo.png\'");
    document.writeln("                                                            alt=\'\'>");
    document.writeln("                                                        <span class=\'pl-3 h5\' style=\'color: #efbe6c;\'>優惠活動</span>");
    document.writeln("                                                        <div class=\'float-right\'><i class=\'fas fa-angle-right\'");
    document.writeln("                                                                style=\'color: #efbe6c;\'></i></div>");
    document.writeln("                                                    </a>");
    document.writeln("                                                </div>");
    document.writeln("                                            </div>");
    document.writeln("                                            <!-- 維護時間 -->");
    document.writeln("                                            <div class=\'row clearfix m-0\'>");
    document.writeln("                                                <div class=\'col-12 p-3 hamburg-border-bottom w-100\'>");
    document.writeln("                                                    <a href=\'../header page/4RepairTime.html\'");
    document.writeln("                                                        class=\'py-3 pl-1 text-decoration-none\'>");
    document.writeln("                                                        <img class=\'img-fluid pl-3\'");
    document.writeln("                                                            src=\'../img/手機index_img/icon3-maintenance.png\' alt=\'\'>");
    document.writeln("                                                        <span class=\'pl-3 h5\' style=\'color: #7dd2e8;\'>維護時間</span>");
    document.writeln("                                                        <div class=\'float-right\'><i class=\'fas fa-angle-right\'");
    document.writeln("                                                                style=\'color: #7dd2e8;\'></i></div>");
    document.writeln("                                                    </a>");
    document.writeln("                                                </div>");
    document.writeln("                                            </div>");
    document.writeln("                                            <!-- 常見問題 -->");
    document.writeln("                                            <div class=\'row clearfix m-0\'>");
    document.writeln("                                                <div class=\'col-12 p-3 hamburg-border-bottom w-100\'>");
    document.writeln("                                                    <a href=\'../header page/3FAQ.html\' class=\'py-3 pl-1 text-decoration-none\'>");
    document.writeln("                                                        <img class=\'img-fluid pl-3\' src=\'../img/手機index_img/icon4-faq.png\'");
    document.writeln("                                                            alt=\'\'>");
    document.writeln("                                                        <span class=\'pl-3 h5\' style=\'color: #9383f3;\'>常見問題</span>");
    document.writeln("                                                        <div class=\'float-right\'><i class=\'fas fa-angle-right\'");
    document.writeln("                                                                style=\'color: #9383f3;\'></i></div>");
    document.writeln("                                                    </a>");
    document.writeln("                                                </div>");
    document.writeln("                                            </div>");
    document.writeln("                                            <!-- 部落格 -->");
    document.writeln("                                            <div class=\'row clearfix m-0\'>");
    document.writeln("                                                <div class=\'col-12 p-3 hamburg-border-bottom w-100\'>");
    document.writeln("                                                    <a href=\'../blog/LiveCasinoBlog.html\'");
    document.writeln("                                                        class=\'py-3 pl-1 text-decoration-none\'>");
    document.writeln("                                                        <img class=\'img-fluid pl-3\' src=\'../img/手機index_img/icon5-blog.png\'");
    document.writeln("                                                            alt=\'\'>");
    document.writeln("                                                        <span class=\'pl-3 h5\' style=\'color: #fb98ac;\'>部落格</span>");
    document.writeln("                                                        <div class=\'float-right\'><i class=\'fas fa-angle-right\'");
    document.writeln("                                                                style=\'color: #fb98ac;\'></i></div>");
    document.writeln("                                                    </a>");
    document.writeln("                                                </div>");
    document.writeln("                                            </div>");
    document.writeln("                                            <!-- APP下載 -->");
    document.writeln("                                            <div class=\'row clearfix m-0\'>");
    document.writeln("                                                <div class=\'col-12 p-3 hamburg-border-bottom w-100\'>");
    document.writeln("                                                    <a href=\'../header page/2AppDownload.html\'");
    document.writeln("                                                        class=\'py-3 pl-1 text-decoration-none\'>");
    document.writeln("                                                        <img class=\'img-fluid pl-3\' src=\'../img/手機index_img/icon6-appdl.png\'");
    document.writeln("                                                            alt=\'\'>");
    document.writeln("                                                        <span class=\'pl-3 h5\' style=\'color: #efbe6c;\'>APP下載</span>");
    document.writeln("                                                        <div class=\'float-right\'><i class=\'fas fa-angle-right\'");
    document.writeln("                                                                style=\'color: #efbe6c;\'></i></div>");
    document.writeln("                                                    </a>");
    document.writeln("                                                </div>");
    document.writeln("                                            </div>");
    document.writeln("                                            <!-- 合營代理 -->");
    document.writeln("                                            <div class=\'row clearfix m-0\'>");
    document.writeln("                                                <div class=\'col-12 p-3 hamburg-border-bottom w-100\'>");
    document.writeln("                                                    <a href=\'../header page/0Agent.html\' class=\'py-3 pl-1 text-decoration-none\'>");
    document.writeln("                                                        <img class=\'img-fluid pl-3\' src=\'../img/手機index_img/icon7-agent.png\'");
    document.writeln("                                                            alt=\'\'>");
    document.writeln("                                                        <span class=\'pl-3 h5\' style=\'color: #7dd2e8;\'>合營代理</span>");
    document.writeln("                                                        <div class=\'float-right\'><i class=\'fas fa-angle-right\'");
    document.writeln("                                                                style=\'color: #7dd2e8;\'></i></div>");
    document.writeln("                                                    </a>");
    document.writeln("                                                </div>");
    document.writeln("                                            </div>");
    document.writeln("                                            <!-- 關於派大金 -->");
    document.writeln("                                            <div class=\'row clearfix m-0\'>");
    document.writeln("                                                <div class=\'col-12 p-3 hamburg-border-bottom w-100\'>");
    document.writeln("                                                    <a href=\'../header page/1AboutUs.html\'");
    document.writeln("                                                        class=\'py-3 pl-1 text-decoration-none\'>");
    document.writeln("                                                        <img class=\'img-fluid pl-3\'");
    document.writeln("                                                            src=\'../img/手機index_img/icon8-Vector Smart Object.png\' alt=\'\'>");
    document.writeln("                                                        <span class=\'pl-3 h5\' style=\'color: #9383f3;\'>關於派大金</span>");
    document.writeln("                                                        <div class=\'float-right\'><i class=\'fas fa-angle-right\'");
    document.writeln("                                                                style=\'color: #9383f3;\'></i></div>");
    document.writeln("                                                    </a>");
    document.writeln("                                                </div>");
    document.writeln("                                            </div>");
    document.writeln("                                            <!-- 登出 -->");
    document.writeln("                                            <div class=\'row clearfix m-0\'>");
    document.writeln("                                                <div class=\'col-12 p-3 w-100\'>");
    document.writeln("                                                    <a class=\'py-3 pl-1 text-decoration-none\' href=\'../index.html\'>");
    document.writeln("                                                        <img class=\'img-fluid pl-3\'");
    document.writeln("                                                            src=\'../img/手機index_img/icon9-sign-out-light.png\' alt=\'\'>");
    document.writeln("                                                        <span class=\'pl-3 h5\' style=\'color: #fb98ac;\'>登出</span>");
    document.writeln("                                                        <div class=\'float-right\'><i class=\'fas fa-angle-right\'");
    document.writeln("                                                                style=\'color: #fb98ac;\'></i></div>");
    document.writeln("                                                    </a>");
    document.writeln("                                                </div>");
    document.writeln("                                            </div>");
    document.writeln("                                        </div>");
    document.writeln("                                    </div>");
    document.writeln("                                </div>");
    document.writeln("                            </div>");
    document.writeln("                        </div>");
    document.writeln("                        <!-- LOGO -->");
    document.writeln("                        <div class=\'col-4 text-center\'>");
    document.writeln("                            <div class=\'text-center\' style=\'margin-left: -5%;\'><a href=\'../index.html\'><img");
    document.writeln("                                        src=\'/123ts/img/手機index_img/派大金LOGO2.png\' alt=\'\' class=\'img-fluid\'></a></div>");
    document.writeln("                        </div>");
    document.writeln("                        <!-- 24HR客服 -->");
    document.writeln("                        <div class=\'col-4\'>");
    document.writeln("                            <div class=\'text-right mr-3\'><img id=\'hrServiceBtn\'");
    document.writeln("                                    src=\'../img/手機index_img/customer-service-a7d0504b43f7ddc70ea0e842b08809f4.png\' alt=\'\'");
    document.writeln("                                    class=\'img-fluid\' data-toggle=\'modal\' data-target=\'#exampleModal\'></div>");
    document.writeln("                        </div>");
    document.writeln("                        <!-- 24HR客服 Modal -->");
    document.writeln("                        <div class=\'modal fade\' id=\'exampleModal\' tabindex=\'-1\' role=\'dialog\'");
    document.writeln("                            aria-labelledby=\'exampleModalLabel\' aria-hidden=\'true\'>");
    document.writeln("                            <div class=\'modal-dialog\' role=\'document\'>");
    document.writeln("                                <div class=\'modal-content mx-auto w-75\'");
    document.writeln("                                    style=\'position: fixed !important;top: 6% !important; left: 10% !important;right: 10% !important;\'>");
    document.writeln("                                    <!-- 聯繫我們 -->");
    document.writeln("                                    <div class=\'modal-header bgc-header-color\'>");
    document.writeln("                                        <p class=\'modal-title m-auto w3-text-pink\' id=\'exampleModalLabel\'");
    document.writeln("                                            style=\'font-size: 1.2rem !important;\'>聯繫我們");
    document.writeln("                                        </p>");
    document.writeln("                                    </div>");
    document.writeln("                                    <!-- img -->");
    document.writeln("                                    <div class=\'modal-body p-0\'>");
    document.writeln("                                        <img src=\'../img/手機index_img/客服側邊-02.png\' alt=\'\' class=\'w-100\'>");
    document.writeln("                                    </div>");
    document.writeln("                                    <!-- Close -->");
    document.writeln("                                    <div class=\'w-100 bgc-header-color\'>");
    document.writeln("                                        <div class=\'py-2 text-center w3-text-pink\' data-dismiss=\'modal\'>Close</div>");
    document.writeln("                                    </div>");
    document.writeln("                                </div>");
    document.writeln("                            </div>");
    document.writeln("                        </div>");
    document.writeln("                    </div>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("        ");
    document.writeln("            <!-- 相通 ------------------------------------------------------------------------>");
    document.writeln("            <!-- marquee -->");
    document.writeln("            <div class=\'container-fluid p-0 m-0 bgc-body-color\'>");
    document.writeln("                <div class=\'container bgc-flex\' style=\'background:url(../img/手機index_img/marqueeBG1.png);\'>");
    document.writeln("                    <div class=\'row p-0 m-0\'>");
    document.writeln("                        <div class=\'text-center\' style=\'width: 12%;padding-top: 0.1em;\'>");
    document.writeln("                            <img src=\'../img/手機index_img/marqueeA.png\' class=\'img-fluid\' alt=\'\'>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'\' style=\'width: 88%;\'>");
    document.writeln("                            <marquee direction=\'left\' height=\'30\' scrollamount=\'5\' behavior=\'left\' class=\'text-light h-100 pt-1\'");
    document.writeln("                                onmouseover=\'this.stop()\' onmouseout=\'this.start()\'>");
    document.writeln("                                【維護公告】 親愛的娛樂城會員您好，【幸運棋牌-維護通知】即刻起進行線路調整緊急維護，維護完成時間待定，造成不便敬請見諒    【存款公告】");
    document.writeln("                                開通超商存款後以第一次繳費地點為綁定超商，若後續要更換繳費超商，請先提前告知與客服申請，否則導致造成資金損失風險需自行承擔，若為附近的超商地點繳費提前告知即可    【存款公告】");
    document.writeln("                                敬愛的卡利會員您好，卡利娛樂城為防堵詐騙氾濫、保障會員資金安全，在此提醒：信用卡、ATM轉帳、VIP專用帳戶存款等服務，務必使用「本人帳戶」！若使用非本人帳戶存款，將一律扣除處理費用後退還本金，感謝您的配合。    【維護公告】");
    document.writeln("                                親愛的會員您好，AV影城將於2020/12/14正式下架，造成不便敬請見諒。    【取款公告】");
    document.writeln("                                親愛的卡利會員您好，由於體育注單會因改判賽事等因素，而進行注單重新結算，因此即日起，卡利娛樂城進行出款時，體育相關注單須全數派彩完畢才處理支付款項，若玩家手上有未派彩注單，麻煩您耐心等候，如有相關疑問、歡迎諮詢24H線上客服，謝謝您。");
    document.writeln("                            </marquee>");
    document.writeln("                        </div>");
    document.writeln("                    </div>");
    document.writeln("                </div>");
    document.writeln("            </div>");
}

// MD Footer
function MDFooter() {
    document.writeln("<!-- 電腦板 footer ------------------------------------------------------------------------>");
    document.writeln("            <!-- footer -->");
    document.writeln("            <div class=\'container-fluid d-none d-md-block p-0 m-0\'");
    document.writeln("                style=\'background:url(../img/桌機index_img/BG2.png) #efe9e9 center top;\'>");
    document.writeln("                <div class=\'container\'>");
    document.writeln("                    <!-- Title -->");
    document.writeln("                    <p class=\'text-light lp2 pt-5 pb-3 centerCenter h5 uk-text-bold\'>合作夥伴</p>");
    document.writeln("                    <!-- 廠商第一列 -->");
    document.writeln("                    <div class=\'row py-3\'>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'https://999xc.net/product/allbet-livecasino\' target=\'_blank\'><img class=\'img-fluid\'");
    document.writeln("                                    src=\'../img/桌機index_img/各廠商/1-01.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'https://999xc.net/product/wm-livecasino\' target=\'_blank\'><img class=\'img-fluid\'");
    document.writeln("                                    src=\'../img/桌機index_img/各廠商/1-02.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'https://999xc.net/product/super-lottery\' target=\'_blank\'><img class=\'img-fluid\'");
    document.writeln("                                    src=\'../img/桌機index_img/各廠商/1-03.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'https://999xc.net/product/rtg-slot\' target=\'_blank\'><img class=\'img-fluid\'");
    document.writeln("                                    src=\'../img/桌機index_img/各廠商/1-04.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'#\' target=\'_blank\'><img class=\'img-fluid\' src=\'../img/桌機index_img/各廠商/1-05.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'https://999xc.net/product/simpleplay-slot\' target=\'_blank\'><img class=\'img-fluid\'");
    document.writeln("                                    src=\'../img/桌機index_img/各廠商/1-06.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'https://999xc.net/product/sa-livecasino\' target=\'_blank\'><img class=\'img-fluid\'");
    document.writeln("                                    src=\'../img/桌機index_img/各廠商/1-07.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'https://999xc.net/product/9k-lottery\' target=\'_blank\'><img class=\'img-fluid\'");
    document.writeln("                                    src=\'../img/桌機index_img/各廠商/1-08.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                    </div>");
    document.writeln("                    <!-- 廠商第二列 -->");
    document.writeln("                    <div class=\'row py-3\'>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'https://999xc.net/product/bwin-slot\' target=\'_blank\'><img class=\'img-fluid\'");
    document.writeln("                                    src=\'../img/桌機index_img/各廠商/1-09.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'https://999xc.net/product/dg-livecasino\' target=\'_blank\'><img class=\'img-fluid\'");
    document.writeln("                                    src=\'../img/桌機index_img/各廠商/1-10.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'https://999xc.net/product/super-sports\' target=\'_blank\'><img class=\'img-fluid\'");
    document.writeln("                                    src=\'../img/桌機index_img/各廠商/1-11.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'#\' target=\'_blank\'><img class=\'img-fluid\' src=\'../img/桌機index_img/各廠商/1-12.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'#\' target=\'_blank\'><img class=\'img-fluid\' src=\'../img/桌機index_img/各廠商/1-13.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'#\' target=\'_blank\'><img class=\'img-fluid\' src=\'../img/桌機index_img/各廠商/1-14.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'https://999xc.net/product/ka-slot\' target=\'_blank\'><img class=\'img-fluid pl-3\'");
    document.writeln("                                    src=\'../img/桌機index_img/各廠商/1-15.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'#\' target=\'_blank\'><img class=\'img-fluid\' src=\'../img/桌機index_img/各廠商/1-16.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                    </div>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("            <div class=\'container-fluid d-none d-md-block p-0 m-0 bg-secondary\'>");
    document.writeln("                <div class=\'container\'>");
    document.writeln("                    <!--  -->");
    document.writeln("                    <div class=\'row\'>");
    document.writeln("                        <a href=\'../header page/Rules.html\' class=\'col py-3\'>");
    document.writeln("                            <p class=\'text-center text-light lp2 uk-text-bold fsz-08\'>條款與規則</p>");
    document.writeln("                        </a>");
    document.writeln("                        <a href=\'../blog/LiveCasinoBlog.html\' class=\'col py-3\'>");
    document.writeln("                            <p class=\'text-center text-light lp2 uk-text-bold fsz-08\'>百家樂</p>");
    document.writeln("                        </a>");
    document.writeln("                        <a href=\'../blog/SportBlog.html\' class=\'col py-3\'>");
    document.writeln("                            <p class=\'text-center text-light lp2 uk-text-bold fsz-08\'>體育投注</p>");
    document.writeln("                        </a>");
    document.writeln("                        <a href=\'../blog/BaccaratTechniquesBlog.html\' class=\'col py-3\'>");
    document.writeln("                            <p class=\'text-center text-light lp2 uk-text-bold fsz-08\'>百家樂技巧</p>");
    document.writeln("                        </a>");
    document.writeln("                        <a href=\'../blog/SlotBlog.html\' class=\'col py-3\'>");
    document.writeln("                            <p class=\'text-center text-light lp2 uk-text-bold fsz-08\'>電子游戲</p>");
    document.writeln("                        </a>");
    document.writeln("                        <a href=\'../blog/GodGamblersBlog.html\' class=\'col py-3\'>");
    document.writeln("                            <p class=\'text-center text-light lp2 uk-text-bold fsz-08\'>賭神大全</p>");
    document.writeln("                        </a>");
    document.writeln("                        <a href=\'../blog/BingoBlog.html\' class=\'col py-3\'>");
    document.writeln("                            <p class=\'text-center text-light lp2 uk-text-bold fsz-08\'>賽車/賓果</p>");
    document.writeln("                        </a>");
    document.writeln("                        <a href=\'../blog/FishBlog.html\' class=\'col py-3\'>");
    document.writeln("                            <p class=\'text-center text-light lp2 uk-text-bold fsz-08\'>捕魚王</p>");
    document.writeln("                        </a>");
    document.writeln("                        <a href=\'../blog/ChessBlog.html\' class=\'col py-3\'>");
    document.writeln("                            <p class=\'text-center text-light lp2 uk-text-bold fsz-08\'>棋牌</p>");
    document.writeln("                        </a>");
    document.writeln("                    </div>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("            <div class=\'container-fluid d-none d-md-block p-0 m-0\'");
    document.writeln("                style=\'background:url(../img/桌機index_img/BG2.png) #efe9e9 center;\'>");
    document.writeln("                <div class=\'container\'>");
    document.writeln("                    <!-- Title -->");
    document.writeln("                    <p class=\'text-light lp2 py-3 centerCenter uk-text-bold fsz-08\' style=\'cursor:no-drop;\'>©派大金版權所有</p>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("        <!-- 手機板 footer ------------------------------------------------------------------------>");
    document.writeln("                <!-- fixed bottom -->");
    document.writeln("                <div class=\'container-fluid d-md-none p-0 m-0 fixed-bottom bgc-body-color\'>");
    document.writeln("                    <div class=\'container\'>");
    document.writeln("                        <div class=\'row p-0 m-0\' id=\'footerHCopy\'>");
    document.writeln("                            <div class=\'col centerCenter py-2 mx-3\'>");
    document.writeln("                                <a href=\'/123ts/index.html\'>");
    document.writeln("                                    <img src=\'/123ts/img/手機index_img/bottom.png\' class=\'img-fluid\' alt=\'\'>");
    document.writeln("                                </a>");
    document.writeln("                            </div>");
    document.writeln("                            <div class=\'col centerCenter py-2 mx-3\'>");
    document.writeln("                                <a href=\'/123ts/page/Promotion.html\'>");
    document.writeln("                                    <img src=\'/123ts/img/手機index_img/bottom1.png\' class=\'img-fluid\' alt=\'\'>");
    document.writeln("                                </a>");
    document.writeln("                            </div>");
    document.writeln("                            <div class=\'col centerCenter py-2 mx-3\'>");
    document.writeln("                                <a href=\'/123ts/page/indexLoginPage.html\'>");
    document.writeln("                                    <img src=\'/123ts/img/手機index_img/bottom2.png\' class=\'img-fluid\' alt=\'\'>");
    document.writeln("                                </a>");
    document.writeln("                            </div>");
    document.writeln("                            <div class=\'col centerCenter py-2 mx-3\'>");
    document.writeln("                                <a href=\'/123ts/header page/Signup.html\'>");
    document.writeln("                                    <img src=\'/123ts/img/手機index_img/bottom3.png\' class=\'img-fluid\' alt=\'\'>");
    document.writeln("                                </a>");
    document.writeln("                            </div>");
    document.writeln("                        </div>");
    document.writeln("                    </div>");
    document.writeln("                </div>");
}

// MD Blog Footer
function MDBlogFooter() {
    document.writeln("<!-- 電腦板 footer ------------------------------------------------------------------------>");
    document.writeln("            <!-- footer -->");
    document.writeln("            <div class=\'container-fluid d-none d-md-block p-0 m-0\'");
    document.writeln("                style=\'background:url(../img/桌機index_img/BG2.png) #efe9e9 center top;\'>");
    document.writeln("                <div class=\'container\'>");
    document.writeln("                    <!-- Title -->");
    document.writeln("                    <p class=\'text-light lp2 pt-5 pb-3 centerCenter h5 uk-text-bold\'>合作夥伴</p>");
    document.writeln("                    <!-- 廠商第一列 -->");
    document.writeln("                    <div class=\'row py-3\'>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'https://999xc.net/product/allbet-livecasino\' target=\'_blank\'><img class=\'img-fluid\'");
    document.writeln("                                    src=\'../img/桌機index_img/各廠商/1-01.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'https://999xc.net/product/wm-livecasino\' target=\'_blank\'><img class=\'img-fluid\'");
    document.writeln("                                    src=\'../img/桌機index_img/各廠商/1-02.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'https://999xc.net/product/super-lottery\' target=\'_blank\'><img class=\'img-fluid\'");
    document.writeln("                                    src=\'../img/桌機index_img/各廠商/1-03.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'https://999xc.net/product/rtg-slot\' target=\'_blank\'><img class=\'img-fluid\'");
    document.writeln("                                    src=\'../img/桌機index_img/各廠商/1-04.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'#\' target=\'_blank\'><img class=\'img-fluid\' src=\'../img/桌機index_img/各廠商/1-05.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'https://999xc.net/product/simpleplay-slot\' target=\'_blank\'><img class=\'img-fluid\'");
    document.writeln("                                    src=\'../img/桌機index_img/各廠商/1-06.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'https://999xc.net/product/sa-livecasino\' target=\'_blank\'><img class=\'img-fluid\'");
    document.writeln("                                    src=\'../img/桌機index_img/各廠商/1-07.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'https://999xc.net/product/9k-lottery\' target=\'_blank\'><img class=\'img-fluid\'");
    document.writeln("                                    src=\'../img/桌機index_img/各廠商/1-08.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                    </div>");
    document.writeln("                    <!-- 廠商第二列 -->");
    document.writeln("                    <div class=\'row py-3\'>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'https://999xc.net/product/bwin-slot\' target=\'_blank\'><img class=\'img-fluid\'");
    document.writeln("                                    src=\'../img/桌機index_img/各廠商/1-09.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'https://999xc.net/product/dg-livecasino\' target=\'_blank\'><img class=\'img-fluid\'");
    document.writeln("                                    src=\'../img/桌機index_img/各廠商/1-10.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'https://999xc.net/product/super-sports\' target=\'_blank\'><img class=\'img-fluid\'");
    document.writeln("                                    src=\'../img/桌機index_img/各廠商/1-11.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'#\' target=\'_blank\'><img class=\'img-fluid\' src=\'../img/桌機index_img/各廠商/1-12.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'#\' target=\'_blank\'><img class=\'img-fluid\' src=\'../img/桌機index_img/各廠商/1-13.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'#\' target=\'_blank\'><img class=\'img-fluid\' src=\'../img/桌機index_img/各廠商/1-14.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'https://999xc.net/product/ka-slot\' target=\'_blank\'><img class=\'img-fluid pl-3\'");
    document.writeln("                                    src=\'../img/桌機index_img/各廠商/1-15.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col my-auto\'>");
    document.writeln("                            <a href=\'#\' target=\'_blank\'><img class=\'img-fluid\' src=\'../img/桌機index_img/各廠商/1-16.png\' alt=\'\'></a>");
    document.writeln("                        </div>");
    document.writeln("                    </div>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("            <div class=\'container-fluid d-none d-md-block p-0 m-0 bg-secondary\'>");
    document.writeln("                <div class=\'container\'>");
    document.writeln("                    <!--  -->");
    document.writeln("                    <div class=\'row\'>");
    document.writeln("                        <a href=\'../header page/Rules.html\' class=\'col py-3\'>");
    document.writeln("                            <p class=\'text-center text-light lp2 uk-text-bold fsz-08\'>條款與規則</p>");
    document.writeln("                        </a>");
    document.writeln("                        <a href=\'../blog/LiveCasinoBlog.html\' class=\'col py-3\'>");
    document.writeln("                            <p class=\'text-center text-light lp2 uk-text-bold fsz-08\'>百家樂</p>");
    document.writeln("                        </a>");
    document.writeln("                        <a href=\'../blog/SportBlog.html\' class=\'col py-3\'>");
    document.writeln("                            <p class=\'text-center text-light lp2 uk-text-bold fsz-08\'>體育投注</p>");
    document.writeln("                        </a>");
    document.writeln("                        <a href=\'../blog/BaccaratTechniquesBlog.html\' class=\'col py-3\'>");
    document.writeln("                            <p class=\'text-center text-light lp2 uk-text-bold fsz-08\'>百家樂技巧</p>");
    document.writeln("                        </a>");
    document.writeln("                        <a href=\'../blog/SlotBlog.html\' class=\'col py-3\'>");
    document.writeln("                            <p class=\'text-center text-light lp2 uk-text-bold fsz-08\'>電子游戲</p>");
    document.writeln("                        </a>");
    document.writeln("                        <a href=\'../blog/GodGamblersBlog.html\' class=\'col py-3\'>");
    document.writeln("                            <p class=\'text-center text-light lp2 uk-text-bold fsz-08\'>賭神大全</p>");
    document.writeln("                        </a>");
    document.writeln("                        <a href=\'../blog/BingoBlog.html\' class=\'col py-3\'>");
    document.writeln("                            <p class=\'text-center text-light lp2 uk-text-bold fsz-08\'>賽車/賓果</p>");
    document.writeln("                        </a>");
    document.writeln("                        <a href=\'../blog/FishBlog.html\' class=\'col py-3\'>");
    document.writeln("                            <p class=\'text-center text-light lp2 uk-text-bold fsz-08\'>捕魚王</p>");
    document.writeln("                        </a>");
    document.writeln("                        <a href=\'../blog/ChessBlog.html\' class=\'col py-3\'>");
    document.writeln("                            <p class=\'text-center text-light lp2 uk-text-bold fsz-08\'>棋牌</p>");
    document.writeln("                        </a>");
    document.writeln("                    </div>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("            <div class=\'container-fluid d-none d-md-block p-0 m-0\'");
    document.writeln("                style=\'background:url(../img/桌機index_img/BG2.png) #efe9e9 center;\'>");
    document.writeln("                <div class=\'container\'>");
    document.writeln("                    <!-- Title -->");
    document.writeln("                    <p class=\'text-light lp2 py-3 centerCenter uk-text-bold fsz-08\' style=\'cursor:no-drop;\'>©派大金版權所有</p>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("        <!-- 手機板 footer ------------------------------------------------------------------------>");
    document.writeln("            <!-- fixed bottom -->");
    document.writeln("            <div class=\'container-fluid d-md-none p-0 m-0 fixed-bottom bgc-body-color\'>");
    document.writeln("                <div class=\'container\'>");
    document.writeln("                    <div class=\'row p-0 m-0\' id=\'footerHCopy\'>");
    document.writeln("                        <div class=\'col centerCenter py-2 mx-3\'>");
    document.writeln("                            <a href=\'/123ts/index.html\'>");
    document.writeln("                                <img src=\'/123ts/img/手機index_img/bottom.png\' class=\'img-fluid\' alt=\'\'>");
    document.writeln("                            </a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col centerCenter py-2 mx-3\'>");
    document.writeln("                            <a href=\'/123ts/page/Promotion.html\'>");
    document.writeln("                                <img src=\'/123ts/img/手機index_img/bottom1.png\' class=\'img-fluid\' alt=\'\'>");
    document.writeln("                            </a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col centerCenter py-2 mx-3\'>");
    document.writeln("                            <a href=\'/123ts/page/indexLoginPage.html\'>");
    document.writeln("                                <img src=\'/123ts/img/手機index_img/bottom2.png\' class=\'img-fluid\' alt=\'\'>");
    document.writeln("                            </a>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'col centerCenter py-2 mx-3\'>");
    document.writeln("                            <a href=\'/123ts/header page/Signup.html\'>");
    document.writeln("                                <img src=\'/123ts/img/手機index_img/bottom3.png\' class=\'img-fluid\' alt=\'\'>");
    document.writeln("                            </a>");
    document.writeln("                        </div>");
    document.writeln("                    </div>");
    document.writeln("                </div>");
    document.writeln("            </div>");
}

// 登入頁面 上方
function indexLoginHeader() {
    document.writeln("<div class=\'container-fluid d-none d-md-block p-0 bgc-header-color\'>");
    document.writeln("                <div class=\'container\'>");
    document.writeln("                    <div class=\'row py-2\'>");
    document.writeln("                        <div class=\'col-12 text-right\'>");
    document.writeln("                            <!--  -->");
    document.writeln("                            <button");
    document.writeln("                                class=\'btn rounded-lg px-4 py-1 fsz-08 text-123ts-color mx-1 w3-hover-text-pink w3-border-orange\'>我的錢包</button>");
    document.writeln("                            <a href=\'../header page/2AppDownload.html\'");
    document.writeln("                                class=\'btn rounded-lg px-4 py-1 fsz-08 text-123ts-color mx-1 w3-hover-text-pink w3-border-orange\'>APP下載</a>");
    document.writeln("                            <!-- user -->");
    document.writeln("                            <span class=\'text-secondary w3-small\'>你好，玩家</span><span");
    document.writeln("                                class=\'text-secondary w3-medium\'>#8868</span>");
    document.writeln("                            <!-- 登出 -->");
    document.writeln("                            <a href=\'../index.html\'><input class=\'input-size ml-2 text-center\'");
    document.writeln("                                    style=\'background-image: url(../img/桌機index_img/btn登入.png);color: #ffbe67;\' type=\'submit\'");
    document.writeln("                                    value=\'登出\'></a>");
    document.writeln("                        </div>");
    document.writeln("                    </div>");
    document.writeln("                </div>");
    document.writeln("            </div>");
}

// 登入頁面 Footer
function indexLoginFooter() {

}