// page頁面 上方
function PageHeader() {
    document.writeln(" <!-- 電腦板 header ------------------------------------------------------------------------>");
    document.writeln("         <!-- login ------------------------------------>");
    document.writeln("<div class=\'container-fluid d-none d-md-block p-0 bgc-loginbar-color\'>");
    document.writeln("    <div class=\'container\'>");
    document.writeln("        <div class=\'row py-1\'>");
    document.writeln("            <div class=\'col-12 text-right\'>");
    document.writeln("                <!-- 帳號 -->");
    document.writeln("                <a href=\'../header page/Signup.html\' target=\'_black\'><input class=\'input-size ml-2 text-center mr-1\'");
    document.writeln("                        style=\'background: url(../卡-img/登入條/註冊.png);\' type=\'button\'></a>");
    document.writeln("                <input type=\'text\' class=\'px-2 input-style\' placeholder=\'用戶名(ID)\' onfocus=\'this.placeholder = ''\'");
    document.writeln("                    onblur=\'this.placeholder = '用戶名(ID)'\' />");
    document.writeln("                <!-- 密碼 -->");
    document.writeln("                <input type=\'password\' class=\'px-2 input-style\' placeholder=\'密碼\' onfocus=\'this.placeholder = ''\'");
    document.writeln("                    onblur=\'this.placeholder = '密碼'\' />");
    document.writeln("                <!-- 登入 -->");
    document.writeln("                <a href=\'../page/indexLogin.html\'><input class=\'input-size2 ml-2 text-center\'");
    document.writeln("                        style=\'background: url(../卡-img/登入條/登入.png);\' type=\'button\'></a>");
    document.writeln("            </div>");
    document.writeln("        </div>");
    document.writeln("    </div>");
    document.writeln("</div>");
    document.writeln(" <!-- LG Navigation Bars ------------------------------------>");
    document.writeln("<div class=\'container-fluid d-none d-lg-block p-0 bgc-header-color NavigationBorder\'>");
    document.writeln("    <div class=\'container\'>");
    document.writeln("        <div class=\'row\' style=\'align-items:center;\'>");
    document.writeln("            <div class=\'col-3 centerCenter\'>");
    document.writeln("                <a class=\'\' href=\'../index.html\'><img class=\'\' src=\'../卡-img/桌機index_img/logo.png\'></a>");
    document.writeln("            </div>");
    document.writeln("            <div class=\'col-9\'>");
    document.writeln("                <div class=\'row mx-auto\'>");
    document.writeln("                    <a class=\'col py-2 centerCenter\' href=\'../page/LiveCasino.html\'>");
    document.writeln("                        <img class=\'img-fluid AnimaTion1\' src=\'../卡-img/桌機index_img/icon1.png\' alt=\'\'>");
    document.writeln("                    </a>");
    document.writeln("                    <a class=\'col py-2 centerCenter\' href=\'../page/Sport.html\'>");
    document.writeln("                        <img class=\'img-fluid AnimaTion2\' src=\'../卡-img/桌機index_img/icon2.png\' alt=\'\'>");
    document.writeln("                    </a>");
    document.writeln("                    <a class=\'col py-2 centerCenter\' href=\'../page/Chess.html\'>");
    document.writeln("                        <img class=\'img-fluid AnimaTion3\' src=\'../卡-img/桌機index_img/icon3.png\' alt=\'\'>");
    document.writeln("                    </a>");
    document.writeln("                    <a class=\'col py-2 centerCenter\' href=\'../page/Slot.html\'>");
    document.writeln("                        <img class=\'img-fluid AnimaTion4\' src=\'../卡-img/桌機index_img/icon4.png\' alt=\'\'></a>");
    document.writeln("                    <a class=\'col py-2 centerCenter\' href=\'../page/Bingo.html\'>");
    document.writeln("                        <img class=\'img-fluid AnimaTion5\' src=\'../卡-img/桌機index_img/icon5.png\' alt=\'\'>");
    document.writeln("                    </a>");
    document.writeln("                    <a class=\'col py-2 centerCenter\' href=\'../page/Fish.html\'>");
    document.writeln("                        <img class=\'img-fluid AnimaTion6\' src=\'../卡-img/桌機index_img/icon6.png\' alt=\'\'>");
    document.writeln("                    </a>");
    document.writeln("                    <a class=\'col py-2 centerCenter\' href=\'../page/Promotion.html\'>");
    document.writeln("                        <img class=\'img-fluid AnimaTion7\' src=\'../卡-img/桌機index_img/icon7.png\' alt=\'\'>");
    document.writeln("                    </a>");
    document.writeln("                    <a class=\'col py-2 centerCenter\' href=\'../page/Movie.html\'>");
    document.writeln("                        <img class=\'img-fluid AnimaTion8\' src=\'../卡-img/桌機index_img/icon8.png\' alt=\'\'>");
    document.writeln("                    </a>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("        </div>");
    document.writeln("    </div>");
    document.writeln("</div>");
    document.writeln("<!-- 維護時間 -->");
    document.writeln("<div class=\'dropleft d-none d-md-block position-absolute\'>");
    document.writeln("    <!-- BMaintenanceTime 控制項 -->");
    document.writeln("    <a class=\'btn BMaintenanceTime p-0\' data-toggle=\'dropdown\' aria-haspopup=\'true\' aria-expanded=\'false\'");
    document.writeln("        id=\'dropdownMenuReference\'><img src=\'../卡-img/桌機index_img/維修.png\' class=\'img-fluid p-0 m-0\' alt=\'\'></a>");
    document.writeln("    <div class=\'dropdown-menu px-3 bgc-header-color\' aria-labelledby=\'dropdownMenuReference\'");
    document.writeln("        style=\'height: 300px; overflow: scroll;overflow-x: hidden;\'>");
    document.writeln("        <div class=\'pt-3\'>");
    document.writeln("            <p class=\'text-center text-light\'>緊急維修</p>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>幸運棋牌</p>");
    document.writeln("            <p class=\'text-center text-light\'>01/12/2020 02:00:00</p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3\'>");
    document.writeln("            <p class=\'text-center\' style=\'height: 1px;width: 100%;background: #555;\'></p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-center\'>星期一</p>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>9K彩票</p>");
    document.writeln("            <p class=\'text-center\'>00:00 至 00:00</p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>Super體育</p>");
    document.writeln("            <p class=\'text-center\'>12:30 至 16:00</p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>WM百家樂</p>");
    document.writeln("            <p class=\'text-center\'>12:00 至 14:30</p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>任你博體育</p>");
    document.writeln("            <p class=\'text-center\'>16:00 至 18:00</p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>六合彩539</p>");
    document.writeln("            <p class=\'text-center\'>12:30 至 16:30</p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>幸運棋牌</p>");
    document.writeln("            <p class=\'text-center\'>23:00 至 00:00</p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>歐博百家樂</p>");
    document.writeln("            <p class=\'text-center\'>08:00 至 12:00</p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>沙龍百家樂</p>");
    document.writeln("            <p class=\'text-center\'>10:00 至 12:30</p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-center\' style=\'height: 1px;width: 100%;background: #555;\'></p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-center\'>星期二</p>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>RTG電子</p>");
    document.writeln("            <p class=\'text-center\'>07:00 至 09:00</p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-center\' style=\'height: 1px;width: 100%;background: #555;\'></p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-center\'>星期三</p>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>DG電子</p>");
    document.writeln("            <p class=\'text-center\'>07:00 至 10:00</p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>MG棋牌</p>");
    document.writeln("            <p class=\'text-center\'>11:00 至 13:00</p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-center\' style=\'height: 1px;width: 100%;background: #555;\'></p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-center\'>星期四</p>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>SimplePlay電子</p>");
    document.writeln("            <p class=\'text-center\'>11:00 至 13:30</p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-center\' style=\'height: 1px;width: 100%;background: #555;\'></p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-center\'>星期五</p>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>SimplePlay電子</p>");
    document.writeln("            <p class=\'text-center\'>15:00 至 19:00</p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'pt-3 text-light\'>");
    document.writeln("            <p class=\'text-center\' style=\'height: 1px;width: 100%;background: #555;\'></p>");
    document.writeln("        </div>");
    document.writeln("        <div class=\'py-3 text-light\'>");
    document.writeln("            <p class=\'text-center\'>星期日</p>");
    document.writeln("            <p class=\'text-black text-center bg-i-gold\'>BNG電子</p>");
    document.writeln("            <p class=\'text-center\'>14:30 至 02:30</p>");
    document.writeln("        </div>");
    document.writeln("    </div>");
    document.writeln("</div>");
    document.writeln("<!-- 聯繫我們 -->");
    document.writeln("<div class=\'d-none d-md-block\'>");
    document.writeln("    <div class=\'contactUs p-1 rounded-right w3-round-large\'>");
    document.writeln("        <!-- 24Hr -->");
    document.writeln("        <a href=\'https://line.me/R/ti/p/%40322gtrqp\' class=\'btn px-0 pt-1 pb-3 m-0 bg-cover\'");
    document.writeln("            style=\'border-bottom: 1px solid #000;\' target=\'_blank\'>");
    document.writeln("            <img src=\'../卡-img/桌機index_img/維修1.png\' class=\'img-fluid\' alt=\'\'>");
    document.writeln("        </a>");
    document.writeln("        <!-- mail -->");
    document.writeln("        <a href=\'#modal-example\' class=\'btn px-1 pt-1 pb-1 pr-2 m-0 bg-cover centerCenter\' uk-toggle>");
    document.writeln("            <img class=\'img-fluid px-1 centerCenter\' src=\'../卡-img/桌機index_img/email.png\' alt=\'\'>");
    document.writeln("        </a>");
    document.writeln("        <!-- 2 modal -->");
    document.writeln("        <div id=\'modal-example\' uk-modal>");
    document.writeln("            <div class=\'uk-modal-dialog uk-modal-body bgc-header-color\'>");
    document.writeln("                <h2 class=\'uk-modal-title text-light\'>意見反饋</h2>");
    document.writeln("                <button class=\'uk-modal-close-default text-light uk-close-large\' style=\'right: 15px; top: 15px;\'");
    document.writeln("                    type=\'button\' uk-close></button>");
    document.writeln("                <!-- table -->");
    document.writeln("                <table class=\'uk-table text-light\'>");
    document.writeln("                    <thead>");
    document.writeln("                        <tr>");
    document.writeln("                            <th class=\'text-light\'></th>");
    document.writeln("                            <th class=\'text-light\'>極差</th>");
    document.writeln("                            <th class=\'text-light\'>很差</th>");
    document.writeln("                            <th class=\'text-light\'>普通</th>");
    document.writeln("                            <th class=\'text-light\'>很好</th>");
    document.writeln("                            <th class=\'text-light\'>極好</th>");
    document.writeln("                        </tr>");
    document.writeln("                    </thead>");
    document.writeln("                    <tbody>");
    document.writeln("                        <tr>");
    document.writeln("                            <td>客服服務</td>");
    document.writeln("                            <td><input type=\'radio\' name=\'1\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'1\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'1\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'1\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'1\' id=\'\'></td>");
    document.writeln("                        </tr>");
    document.writeln("                        <tr>");
    document.writeln("                            <td>提款速度</td>");
    document.writeln("                            <td><input type=\'radio\' name=\'2\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'2\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'2\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'2\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'2\' id=\'\'></td>");
    document.writeln("                        </tr>");
    document.writeln("                        <tr>");
    document.writeln("                            <td>操作界面</td>");
    document.writeln("                            <td><input type=\'radio\' name=\'3\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'3\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'3\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'3\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'3\' id=\'\'></td>");
    document.writeln("                        </tr>");
    document.writeln("                        <tr>");
    document.writeln("                            <td>網路連結速度</td>");
    document.writeln("                            <td><input type=\'radio\' name=\'4\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'4\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'4\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'4\' id=\'\'></td>");
    document.writeln("                            <td><input type=\'radio\' name=\'4\' id=\'\'></td>");
    document.writeln("                        </tr>");
    document.writeln("                    </tbody>");
    document.writeln("                </table>");
    document.writeln("                <div class=\'row pb-3\'>");
    document.writeln("                    <div class=\'col-3 text-light ml-3\'>意見</div>");
    document.writeln("                    <div class=\'flex-grow-1\'>");
    document.writeln("                        <textarea name=\'\' id=\'\' cols=\'39\' rows=\'5\'></textarea>");
    document.writeln("                    </div>");
    document.writeln("                </div>");
    document.writeln("                <p class=\'uk-text-right\'>");
    document.writeln("                    <button class=\'uk-button bg-i-gold text-black\' type=\'button\'>提交</button>");
    document.writeln("                </p>");
    document.writeln("            </div>");
    document.writeln("        </div>");
    document.writeln("    </div>");
    document.writeln("</div>");
    document.writeln("<!-- 手機板 header ------------------------------------------------------------------------>");
    document.writeln("<!-- MD Navigation Bars ------------------------------------>");
    document.writeln("<div class=\'container-fluid p-0 d-lg-none bgc-header-color MdNavigationBorder\'>");
    document.writeln("    <div class=\'container\'>");
    document.writeln("        <div class=\'row py-2\' style=\'align-items: center;\'>");
    document.writeln("            <!-- 漢堡圖 -->");
    document.writeln("            <div class=\'col-4 text-left\'>");
    document.writeln("                <!-- HamburgBtn -->");
    document.writeln("                <i class=\'fas fa-bars fa-2x\' style=\'color:#f1cd6d\' id=\'HamburgBtn\' data-toggle=\'modal\'");
    document.writeln("                    data-target=\'#exampleModal0\'></i>");
    document.writeln("                <!-- HamburgBtn modal -->");
    document.writeln("                <div class=\'modal\' id=\'exampleModal0\'>");
    document.writeln("                    <div id=\'showMenu p-0\' class=\'modal-dialog\'>");
    document.writeln("                        <div class=\'showMenuList modal-content\'>");
    document.writeln("                            <div class=\'modal-body p-0 m-0\'>");
    document.writeln("                                <!-- 關閉 -->");
    document.writeln("                                <!-- <div class=\'w-100\'>");
    document.writeln("                                    <div class=\'pb-2 pt-1 pr-3 text-light text-right\' data-dismiss=\'modal\'><i");
    document.writeln("                                            class=\'fas fa-times text-light\'></i></div>");
    document.writeln("                                </div> -->");
    document.writeln("                                <!-- 派大金logo -->");
    document.writeln("                                <div class=\'row m-0 px-5 py-3 bgc-body-color hamburg-border-bottom\'");
    document.writeln("                                    style=\'box-shadow: 0 1px 5px rgba(83, 83, 83, 0.041);\'>");
    document.writeln("                                    <img class=\'centerCenter img-fluid\' src=\'/123ts/img/手機index_img/派大金LOGO2.png\'");
    document.writeln("                                        alt=\'\'>");
    document.writeln("                                </div>");
    document.writeln("                                <!-- LiveCasino -->");
    document.writeln("                                <div class=\'row clearfix m-0\'>");
    document.writeln("                                    <div class=\'col-12 px-3 py-2 hamburg-border-bottom w-100\'>");
    document.writeln("                                        <a class=\'py-3 pl-1 text-decoration-none\' href=\'../index.html\'>");
    document.writeln("                                            <img class=\'img-fluid pl-3\' src=\'./img/手機index_img/icon1-home.png\'");
    document.writeln("                                                alt=\'\'>");
    document.writeln("                                            <span class=\'pl-3\' style=\'color: #fb98ac;\'>首頁</span>");
    document.writeln("                                            <div class=\'float-right\'><i class=\'fas fa-angle-right\'");
    document.writeln("                                                    style=\'color: #fb98ac;\'></i></div>");
    document.writeln("                                        </a>");
    document.writeln("                                    </div>");
    document.writeln("                                </div>");
    document.writeln("                                <!-- 優惠活動 -->");
    document.writeln("                                <div class=\'row clearfix m-0\'>");
    document.writeln("                                    <div class=\'col-12 px-3 py-2 hamburg-border-bottom w-100\'>");
    document.writeln("                                        <a class=\'py-3 pl-1 text-decoration-none\' href=\'../page/Promotion.html\'>");
    document.writeln("                                            <img class=\'img-fluid pl-3\' src=\'./img/手機index_img/icon2-promo.png\'");
    document.writeln("                                                alt=\'\'>");
    document.writeln("                                            <span class=\'pl-3\' style=\'color: #efbe6c;\'>優惠活動</span>");
    document.writeln("                                            <div class=\'float-right\'><i class=\'fas fa-angle-right\'");
    document.writeln("                                                    style=\'color: #efbe6c;\'></i></div>");
    document.writeln("                                        </a>");
    document.writeln("                                    </div>");
    document.writeln("                                </div>");
    document.writeln("                                <!-- 維護時間 -->");
    document.writeln("                                <div class=\'row clearfix m-0\'>");
    document.writeln("                                    <div class=\'col-12 px-3 py-2 hamburg-border-bottom w-100\'>");
    document.writeln("                                        <a class=\'py-3 pl-1 text-decoration-none\'");
    document.writeln("                                            href=\'../header page/4RepairTime.html\'>");
    document.writeln("                                            <img class=\'img-fluid pl-3\'");
    document.writeln("                                                src=\'./img/手機index_img/icon3-maintenance.png\' alt=\'\'>");
    document.writeln("                                            <span class=\'pl-3\' style=\'color: #7dd2e8;\'>維護時間</span>");
    document.writeln("                                            <div class=\'float-right\'><i class=\'fas fa-angle-right\'");
    document.writeln("                                                    style=\'color: #7dd2e8;\'></i></div>");
    document.writeln("                                        </a>");
    document.writeln("                                    </div>");
    document.writeln("                                </div>");
    document.writeln("                                <!-- 常見問題 -->");
    document.writeln("                                <div class=\'row clearfix m-0\'>");
    document.writeln("                                    <div class=\'col-12 px-3 py-2 hamburg-border-bottom w-100\'>");
    document.writeln("                                        <a class=\'py-3 pl-1 text-decoration-none\' href=\'../header page/3FAQ.html\'>");
    document.writeln("                                            <img class=\'img-fluid pl-3\' src=\'./img/手機index_img/icon4-faq.png\'");
    document.writeln("                                                alt=\'\'>");
    document.writeln("                                            <span class=\'pl-3\' style=\'color: #9383f3;\'>常見問題</span>");
    document.writeln("                                            <div class=\'float-right\'><i class=\'fas fa-angle-right\'");
    document.writeln("                                                    style=\'color: #9383f3;\'></i></div>");
    document.writeln("                                        </a>");
    document.writeln("                                    </div>");
    document.writeln("                                </div>");
    document.writeln("                                <!-- 部落格 -->");
    document.writeln("                                <div class=\'row clearfix m-0\'>");
    document.writeln("                                    <div class=\'col-12 px-3 py-2 hamburg-border-bottom w-100\'>");
    document.writeln("                                        <a class=\'py-3 pl-1 text-decoration-none\' href=\'../blog/LiveCasinoBlog.html\'>");
    document.writeln("                                            <img class=\'img-fluid pl-3\' src=\'./img/手機index_img/icon5-blog.png\'");
    document.writeln("                                                alt=\'\'>");
    document.writeln("                                            <span class=\'pl-3\' style=\'color: #fb98ac;\'>部落格</span>");
    document.writeln("                                            <div class=\'float-right\'><i class=\'fas fa-angle-right\'");
    document.writeln("                                                    style=\'color: #fb98ac;\'></i></div>");
    document.writeln("                                        </a>");
    document.writeln("                                    </div>");
    document.writeln("                                </div>");
    document.writeln("                                <!-- APP下載 -->");
    document.writeln("                                <div class=\'row clearfix m-0\'>");
    document.writeln("                                    <div class=\'col-12 px-3 py-2 hamburg-border-bottom w-100\'>");
    document.writeln("                                        <a class=\'py-3 pl-1 text-decoration-none\'");
    document.writeln("                                            href=\'../header page/2AppDownload.html\'>");
    document.writeln("                                            <img class=\'img-fluid pl-3\' src=\'./img/手機index_img/icon6-appdl.png\'");
    document.writeln("                                                alt=\'\'>");
    document.writeln("                                            <span class=\'pl-3\' style=\'color: #efbe6c;\'>APP下載</span>");
    document.writeln("                                            <div class=\'float-right\'><i class=\'fas fa-angle-right\'");
    document.writeln("                                                    style=\'color: #efbe6c;\'></i></div>");
    document.writeln("                                        </a>");
    document.writeln("                                    </div>");
    document.writeln("                                </div>");
    document.writeln("                                <!-- 合營代理 -->");
    document.writeln("                                <div class=\'row clearfix m-0\'>");
    document.writeln("                                    <div class=\'col-12 px-3 py-2 hamburg-border-bottom w-100\'>");
    document.writeln("                                        <a class=\'py-3 pl-1 text-decoration-none\' href=\'../header page/0Agent.html\'>");
    document.writeln("                                            <img class=\'img-fluid pl-3\' src=\'./img/手機index_img/icon7-agent.png\'");
    document.writeln("                                                alt=\'\'>");
    document.writeln("                                            <span class=\'pl-3\' style=\'color: #7dd2e8;\'>合營代理</span>");
    document.writeln("                                            <div class=\'float-right\'><i class=\'fas fa-angle-right\'");
    document.writeln("                                                    style=\'color: #7dd2e8;\'></i></div>");
    document.writeln("                                        </a>");
    document.writeln("                                    </div>");
    document.writeln("                                </div>");
    document.writeln("                                <!-- 關於派大金 -->");
    document.writeln("                                <div class=\'row clearfix m-0\'>");
    document.writeln("                                    <div class=\'col-12 px-3 py-2 hamburg-border-bottom w-100\'>");
    document.writeln("                                        <a class=\'py-3 pl-1 text-decoration-none\'");
    document.writeln("                                            href=\'../header page/1AboutUs.html\'>");
    document.writeln("                                            <img class=\'img-fluid pl-3\'");
    document.writeln("                                                src=\'./img/手機index_img/icon8-Vector Smart Object.png\' alt=\'\'>");
    document.writeln("                                            <span class=\'pl-3\' style=\'color: #9383f3;\'>關於派大金</span>");
    document.writeln("                                            <div class=\'float-right\'><i class=\'fas fa-angle-right\'");
    document.writeln("                                                    style=\'color: #9383f3;\'></i></div>");
    document.writeln("                                        </a>");
    document.writeln("                                    </div>");
    document.writeln("                                </div>");
    document.writeln("                                <!-- 登出 -->");
    document.writeln("                                <div class=\'row clearfix m-0\'>");
    document.writeln("                                    <div class=\'col-12 px-3 py-2 w-100\'>");
    document.writeln("                                        <a class=\'py-3 pl-1 text-decoration-none\' href=\'../index.html\'>");
    document.writeln("                                            <img class=\'img-fluid pl-3\'");
    document.writeln("                                                src=\'./img/手機index_img/icon9-sign-out-light.png\' alt=\'\'>");
    document.writeln("                                            <span class=\'pl-3\' style=\'color: #fb98ac;\'>登出</span>");
    document.writeln("                                            <div class=\'float-right\'><i class=\'fas fa-angle-right\'");
    document.writeln("                                                    style=\'color: #fb98ac;\'></i></div>");
    document.writeln("                                        </a>");
    document.writeln("                                    </div>");
    document.writeln("                                </div>");
    document.writeln("                            </div>");
    document.writeln("                        </div>");
    document.writeln("                    </div>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("            <!-- LOGO -->");
    document.writeln("            <div class=\'col-4 text-center\'>");
    document.writeln("                <div class=\'text-center\' style=\'margin-left: -5%;\'><a href=\'../index.html\'><img");
    document.writeln("                            src=\'../卡-img/手機index_img/logo.png\' alt=\'\' class=\'img-fluid\'></a></div>");
    document.writeln("            </div>");
    document.writeln("            <!-- 24HR客服 -->");
    document.writeln("            <div class=\'col-4\'>");
    document.writeln("                <div class=\'text-right mr-3\'><img id=\'hrServiceBtn\' src=\'../卡-img/手機index_img/24h.png\' alt=\'\'");
    document.writeln("                        class=\'img-fluid\' data-toggle=\'modal\' data-target=\'#exampleModal\'></div>");
    document.writeln("            </div>");
    document.writeln("            <!-- 24HR客服 Modal -->");
    document.writeln("            <div class=\'modal fade\' id=\'exampleModal\' tabindex=\'-1\' role=\'dialog\'");
    document.writeln("                aria-labelledby=\'exampleModalLabel\' aria-hidden=\'true\'>");
    document.writeln("                <div class=\'modal-dialog\' role=\'document\'>");
    document.writeln("                    <div class=\'modal-content mx-auto w-75\'");
    document.writeln("                        style=\'position: fixed !important;top: 6% !important; left: 10% !important;right: 10% !important;\'>");
    document.writeln("                        <!-- 聯繫我們 -->");
    document.writeln("                        <div class=\'modal-header bgc-header-color\'>");
    document.writeln("                            <p class=\'modal-title m-auto w3-text-white\' id=\'exampleModalLabel\'");
    document.writeln("                                style=\'font-size: 1.2rem !important;\'>聯繫我們");
    document.writeln("                            </p>");
    document.writeln("                        </div>");
    document.writeln("                        <!-- img -->");
    document.writeln("                        <div class=\'modal-body p-0\'>");
    document.writeln("                            <img src=\'../卡-img/手機index_img/24x7.png\' alt=\'\' class=\'w-100\'>");
    document.writeln("                        </div>");
    document.writeln("                        <!-- Close -->");
    document.writeln("                        <div class=\'w-100 bgc-header-color\'>");
    document.writeln("                            <div class=\'py-2 text-center w3-text-white\' style=\'cursor: pointer;\'");
    document.writeln("                                data-dismiss=\'modal\'>Close</div>");
    document.writeln("                        </div>");
    document.writeln("                    </div>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("        </div>");
    document.writeln("    </div>");
    document.writeln("</div>");
    document.writeln("<!-- banner -->");
    document.writeln("<div class=\'container-fluid p-0 d-md-none MdNavigationBorder\'>");
    document.writeln("    <div id=\'carouselExampleControls\' class=\'carousel slide\' data-ride=\'carousel\'>");
    document.writeln("        <div class=\'carousel-inner\'>");
    document.writeln("            <div class=\'carousel-item active\'>");
    document.writeln("                <img src=\'./img/手機index_img/banner.png\' class=\'d-block w-100\' alt=\'...\'>");
    document.writeln("            </div>");
    document.writeln("            <div class=\'carousel-item\'>");
    document.writeln("                <img src=\'./img/手機index_img/banner1.jpg\' class=\'d-block w-100\' alt=\'...\'>");
    document.writeln("            </div>");
    document.writeln("            <div class=\'carousel-item\'>");
    document.writeln("                <img src=\'./img/手機index_img/banner2.webp\' class=\'d-block w-100\' alt=\'...\'>");
    document.writeln("            </div>");
    document.writeln("        </div>");
    document.writeln("        <a class=\'carousel-control-prev\' href=\'#carouselExampleControls\' role=\'button\' data-slide=\'prev\'>");
    document.writeln("            <span class=\'carousel-control-prev-icon\' aria-hidden=\'true\'></span>");
    document.writeln("            <span class=\'sr-only\'>Previous</span>");
    document.writeln("        </a>");
    document.writeln("        <a class=\'carousel-control-next\' href=\'#carouselExampleControls\' role=\'button\' data-slide=\'next\'>");
    document.writeln("            <span class=\'carousel-control-next-icon\' aria-hidden=\'true\'></span>");
    document.writeln("            <span class=\'sr-only\'>Next</span>");
    document.writeln("        </a>");
    document.writeln("    </div>");
    document.writeln("</div>");
    document.writeln("<!-- 相通 ------------------------------------------------------------------------>");
    document.writeln("<!-- marquee -->");
    document.writeln("<div class=\'container-fluid p-0 m-0\'>");
    document.writeln("    <div class=\'bgc-flex\' style=\'background-color: black; height: 28px;\'>");
    document.writeln("        <div class=\'row p-0 m-0\'>");
    document.writeln("            <div class=\'text-center\' style=\'width: 10%;\'>");
    document.writeln("                <img src=\'./img/手機index_img/marqueeA.png\' class=\'img-fluid\' alt=\'\'>");
    document.writeln("            </div>");
    document.writeln("            <div class=\'\' style=\'width: 88%;\'>");
    document.writeln("                <marquee direction=\'left\' height=\'10\' scrollamount=\'5\' behavior=\'left\' class=\'text-light h-100\'");
    document.writeln("                    onmouseover=\'this.stop()\' onmouseout=\'this.start()\'>");
    document.writeln("                    【維護公告】 親愛的娛樂城會員您好，【幸運棋牌-維護通知】即刻起進行線路調整緊急維護，維護完成時間待定，造成不便敬請見諒    【存款公告】");
    document.writeln("                    開通超商存款後以第一次繳費地點為綁定超商，若後續要更換繳費超商，請先提前告知與客服申請，否則導致造成資金損失風險需自行承擔，若為附近的超商地點繳費提前告知即可    【存款公告】");
    document.writeln("                    敬愛的卡利會員您好，卡利娛樂城為防堵詐騙氾濫、保障會員資金安全，在此提醒：信用卡、ATM轉帳、VIP專用帳戶存款等服務，務必使用「本人帳戶」！若使用非本人帳戶存款，將一律扣除處理費用後退還本金，感謝您的配合。    【維護公告】");
    document.writeln("                    親愛的會員您好，AV影城將於2020/12/14正式下架，造成不便敬請見諒。    【取款公告】");
    document.writeln("                    親愛的卡利會員您好，由於體育注單會因改判賽事等因素，而進行注單重新結算，因此即日起，卡利娛樂城進行出款時，體育相關注單須全數派彩完畢才處理支付款項，若玩家手上有未派彩注單，麻煩您耐心等候，如有相關疑問、歡迎諮詢24H線上客服，謝謝您。");
    document.writeln("                </marquee>");
    document.writeln("            </div>");
    document.writeln("        </div>");
    document.writeln("    </div>");
    document.writeln("</div>");
}

// 登入頁面 Footer
function indexLoginFooter() {

}